package uk.org.rnib.innovation.fileopener;

import java.io.ByteArrayInputStream;
import java.io.InputStream;

public class MockFileOpener implements FileOpener {

	public InputStream open(String path){
		String text = null;
		String name = path.substring(path.lastIndexOf("/") + 1); 
		if (name.equals("speechgen.opf"))
			text = SPEECHGEN_OPF;
		if (name.equals("speechgen.ncx"))
			text = SPEECHGEN_NCX;
		if (name.equals("speechgen0002.smil"))
			text = SPEECHGEN0002_SMIL;
		if (name.equals("speechgen0003.smil"))
			text = SPEECHGEN0003_SMIL;
		if (name.equals("speechgen0007.smil"))
			text = SPEECHGEN0007_SMIL;
		if (name.equals("speechgen0008.smil"))
			text = SPEECHGEN0008_SMIL;
		if (name.equals("AreYouReadyV3.xml"))
			text = AREYOUREADYV3_XML;
		return new ByteArrayInputStream(text.getBytes());
	}

	private final String SPEECHGEN_OPF
	= "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
	+ "<!DOCTYPE package"
	+ "  PUBLIC \"+//ISBN 0-9673008-1-9//DTD OEB 1.2 Package//EN\" \"http://openebook.org/dtds/oeb-1.2/oebpkg12.dtd\">"
	+ "<package xmlns=\"http://openebook.org/namespaces/oeb-package/1.0/\" unique-identifier=\"uid\">"
	+ "	  <metadata>"
	+ "	"
	+ "		    <dc-metadata xmlns:dc=\"http://purl.org/dc/elements/1.1/\""
	+ "                   xmlns:oebpackage=\"http://openebook.org/namespaces/oeb-package/1.0/\">"
	+ "			      <dc:Format>ANSI/NISO Z39.86-2005</dc:Format>"
	+ "		       <dc:Language>en-IN</dc:Language>"
	+ "         <dc:Date>2009-04-26</dc:Date>"
	+ "         <dc:Creator>WikiHow</dc:Creator>"
	+ "         <dc:Publisher>DAISY India</dc:Publisher>"
	+ "         <dc:Title>ARE YOU READY?</dc:Title>"
	+ "         <dc:Subject>A Short Manual for Disaster Management</dc:Subject>"
	+ "         <dc:Identifier>5078727220897727718</dc:Identifier>"
	+ "         <dc:Identifier id=\"uid\">AUTO-UID-4767990567747899000</dc:Identifier>"
	+ "      </dc-metadata>"
	+ "	"
	+ "		    <x-metadata>"
	+ "			      <meta content=\"audioFullText\" name=\"dtb:multimediaType\"/>"
	+ "			      <meta content=\"DAISY Pipeline Narrator\" name=\"dtb:narrator\"/>"
	+ "		       <meta content=\"0:50:27.083\" name=\"dtb:totalTime\"/>"
	+ "         <meta content=\"audio,text,image\" name=\"dtb:multimediaContent\"/>"
	+ "      </x-metadata>"
	+ "	"
	+ "	  </metadata>"
	+ "	"
	+ "	  <manifest>"
	+ "	     <item href=\"speechgen0001.smil\" id=\"smil-1\" media-type=\"application/smil\"/>"
	+ "      <item href=\"speechgen0002.smil\" id=\"smil-2\" media-type=\"application/smil\"/>"
	+ "      <item href=\"speechgen0003.smil\" id=\"smil-3\" media-type=\"application/smil\"/>"
	+ "      <item href=\"speechgen0004.smil\" id=\"smil-4\" media-type=\"application/smil\"/>"
	+ "      <item href=\"speechgen0005.smil\" id=\"smil-5\" media-type=\"application/smil\"/>"
	+ "      <item href=\"speechgen0006.smil\" id=\"smil-6\" media-type=\"application/smil\"/>"
	+ "      <item href=\"speechgen0007.smil\" id=\"smil-7\" media-type=\"application/smil\"/>"
	+ "      <item href=\"speechgen0008.smil\" id=\"smil-8\" media-type=\"application/smil\"/>"
	+ "      <item href=\"speechgen0009.smil\" id=\"smil-9\" media-type=\"application/smil\"/>"
	+ "      <item href=\"speechgen0010.smil\" id=\"smil-10\" media-type=\"application/smil\"/>"
	+ "      <item href=\"speechgen0011.smil\" id=\"smil-11\" media-type=\"application/smil\"/>"
	+ "      <item href=\"speechgen0012.smil\" id=\"smil-12\" media-type=\"application/smil\"/>"
	+ "      <item href=\"speechgen0013.smil\" id=\"smil-13\" media-type=\"application/smil\"/>"
	+ "      <item href=\"speechgen0014.smil\" id=\"smil-14\" media-type=\"application/smil\"/>"
	+ "      <item href=\"speechgen0015.smil\" id=\"smil-15\" media-type=\"application/smil\"/>"
	+ "      <item href=\"speechgen0016.smil\" id=\"smil-16\" media-type=\"application/smil\"/>"
	+ "      <item href=\"speechgen0017.smil\" id=\"smil-17\" media-type=\"application/smil\"/>"
	+ "      <item href=\"speechgen0018.smil\" id=\"smil-18\" media-type=\"application/smil\"/>"
	+ "      <item href=\"speechgen0019.smil\" id=\"smil-19\" media-type=\"application/smil\"/>"
	+ "      <item href=\"speechgen0020.smil\" id=\"smil-20\" media-type=\"application/smil\"/>"
	+ "      <item href=\"speechgen0021.smil\" id=\"smil-21\" media-type=\"application/smil\"/>"
	+ "      <item href=\"speechgen0022.smil\" id=\"smil-22\" media-type=\"application/smil\"/>"
	+ "      <item href=\"speechgen0023.smil\" id=\"smil-23\" media-type=\"application/smil\"/>"
	+ "      <item href=\"speechgen0024.smil\" id=\"smil-24\" media-type=\"application/smil\"/>"
	+ "      <item href=\"speechgen0025.smil\" id=\"smil-25\" media-type=\"application/smil\"/>"
	+ "      <item href=\"speechgen0026.smil\" id=\"smil-26\" media-type=\"application/smil\"/>"
	+ "      <item href=\"speechgen0027.smil\" id=\"smil-27\" media-type=\"application/smil\"/>"
	+ "      <item href=\"speechgen0028.smil\" id=\"smil-28\" media-type=\"application/smil\"/>"
	+ "      <item href=\"speechgen0029.smil\" id=\"smil-29\" media-type=\"application/smil\"/>"
	+ "      <item href=\"speechgen0030.smil\" id=\"smil-30\" media-type=\"application/smil\"/>"
	+ "      <item href=\"speechgen0031.smil\" id=\"smil-31\" media-type=\"application/smil\"/>"
	+ "      <item href=\"speechgen0032.smil\" id=\"smil-32\" media-type=\"application/smil\"/>"
	+ "      <item href=\"speechgen0033.smil\" id=\"smil-33\" media-type=\"application/smil\"/>"
	+ "      <item href=\"speechgen0034.smil\" id=\"smil-34\" media-type=\"application/smil\"/>"
	+ "      <item href=\"speechgen0002.mp3\" id=\"opf-35\" media-type=\"audio/mpeg\"/>"
	+ "      <item href=\"speechgen.ncx\" id=\"ncx\" media-type=\"application/x-dtbncx+xml\"/>"
	+ "      <item href=\"speechgen0014.mp3\" id=\"opf-36\" media-type=\"audio/mpeg\"/>"
	+ "      <item href=\"image5.jpg\" id=\"opf-37\" media-type=\"image/jpeg\"/>"
	+ "      <item href=\"image2.jpg\" id=\"opf-38\" media-type=\"image/jpeg\"/>"
	+ "      <item href=\"image11.jpg\" id=\"opf-39\" media-type=\"image/jpeg\"/>"
	+ "      <item href=\"speechgen0006.mp3\" id=\"opf-40\" media-type=\"audio/mpeg\"/>"
	+ "      <item href=\"speechgen0022.mp3\" id=\"opf-41\" media-type=\"audio/mpeg\"/>"
	+ "      <item href=\"speechgen0030.mp3\" id=\"opf-42\" media-type=\"audio/mpeg\"/>"
	+ "      <item href=\"speechgen0013.mp3\" id=\"opf-43\" media-type=\"audio/mpeg\"/>"
	+ "      <item href=\"speechgen0018.mp3\" id=\"opf-44\" media-type=\"audio/mpeg\"/>"
	+ "      <item href=\"image4.jpg\" id=\"opf-45\" media-type=\"image/jpeg\"/>"
	+ "      <item href=\"speechgen0023.mp3\" id=\"opf-46\" media-type=\"audio/mpeg\"/>"
	+ "      <item href=\"speechgen0007.mp3\" id=\"opf-47\" media-type=\"audio/mpeg\"/>"
	+ "      <item href=\"speechgen0033.mp3\" id=\"opf-48\" media-type=\"audio/mpeg\"/>"
	+ "      <item href=\"speechgen0012.mp3\" id=\"opf-49\" media-type=\"audio/mpeg\"/>"
	+ "      <item href=\"speechgen0020.mp3\" id=\"opf-50\" media-type=\"audio/mpeg\"/>"
	+ "      <item href=\"image13.jpg\" id=\"opf-51\" media-type=\"image/jpeg\"/>"
	+ "      <item href=\"speechgen.opf\" id=\"opf-52\" media-type=\"text/xml\"/>"
	+ "      <item href=\"speechgen0016.mp3\" id=\"opf-53\" media-type=\"audio/mpeg\"/>"
	+ "      <item href=\"speechgen0024.mp3\" id=\"opf-54\" media-type=\"audio/mpeg\"/>"
	+ "      <item href=\"speechgen0028.mp3\" id=\"opf-55\" media-type=\"audio/mpeg\"/>"
	+ "      <item href=\"speechgen0003.mp3\" id=\"opf-56\" media-type=\"audio/mpeg\"/>"
	+ "      <item href=\"speechgen0021.mp3\" id=\"opf-57\" media-type=\"audio/mpeg\"/>"
	+ "      <item href=\"speechgen0034.mp3\" id=\"opf-58\" media-type=\"audio/mpeg\"/>"
	+ "      <item href=\"tpbnarrator_res.mp3\" id=\"opf-59\" media-type=\"audio/mpeg\"/>"
	+ "      <item href=\"image3.jpg\" id=\"opf-60\" media-type=\"image/jpeg\"/>"
	+ "      <item href=\"speechgen0017.mp3\" id=\"opf-61\" media-type=\"audio/mpeg\"/>"
	+ "      <item href=\"speechgen0011.mp3\" id=\"opf-62\" media-type=\"audio/mpeg\"/>"
	+ "      <item href=\"image12.jpg\" id=\"opf-63\" media-type=\"image/jpeg\"/>"
	+ "      <item href=\"speechgen0015.mp3\" id=\"opf-64\" media-type=\"audio/mpeg\"/>"
	+ "      <item href=\"speechgen0004.mp3\" id=\"opf-65\" media-type=\"audio/mpeg\"/>"
	+ "      <item href=\"speechgen0031.mp3\" id=\"opf-66\" media-type=\"audio/mpeg\"/>"
	+ "      <item href=\"speechgen0009.mp3\" id=\"opf-67\" media-type=\"audio/mpeg\"/>"
	+ "      <item href=\"speechgen0032.mp3\" id=\"opf-68\" media-type=\"audio/mpeg\"/>"
	+ "      <item href=\"speechgen0019.mp3\" id=\"opf-69\" media-type=\"audio/mpeg\"/>"
	+ "      <item href=\"image14.jpg\" id=\"opf-70\" media-type=\"image/jpeg\"/>"
	+ "      <!-- item href=\"tpbnarrator.res\" id=\"resource\" media-type=\"application/x-dtbresource+xml\"/ -->"
	+ "	  <item href=\"resource.xml\" id=\"resource\" media-type=\"application/x-dtbresource+xml\"/>"
	+ "      <item href=\"speechgen0001.mp3\" id=\"opf-71\" media-type=\"audio/mpeg\"/>"
	+ "      <item href=\"speechgen0008.mp3\" id=\"opf-72\" media-type=\"audio/mpeg\"/>"
	+ "      <item href=\"speechgen0027.mp3\" id=\"opf-73\" media-type=\"audio/mpeg\"/>"
	+ "      <item href=\"image1.jpg\" id=\"opf-74\" media-type=\"image/jpeg\"/>"
	+ "      <item href=\"speechgen0005.mp3\" id=\"opf-75\" media-type=\"audio/mpeg\"/>"
	+ "      <item href=\"speechgen0029.mp3\" id=\"opf-76\" media-type=\"audio/mpeg\"/>"
	+ "      <item href=\"speechgen0010.mp3\" id=\"opf-77\" media-type=\"audio/mpeg\"/>"
	+ "      <item href=\"speechgen0025.mp3\" id=\"opf-78\" media-type=\"audio/mpeg\"/>"
	+ "      <item href=\"dtbookbasic.css\" id=\"opf-79\" media-type=\"text/css\"/>"
	+ "      <item href=\"speechgen0026.mp3\" id=\"opf-80\" media-type=\"audio/mpeg\"/>"
	+ "      <item href=\"AreYouReadyV3.xml\" id=\"opf-81\" media-type=\"application/x-dtbook+xml\"/>"
	+ "   </manifest>"
	+ "	"
	+ "	  <spine>"
	+ "	     <itemref idref=\"smil-1\"/>"
	+ "      <itemref idref=\"smil-2\"/>"
	+ "      <itemref idref=\"smil-3\"/>"
	+ "      <itemref idref=\"smil-4\"/>"
	+ "      <itemref idref=\"smil-5\"/>"
	+ "      <itemref idref=\"smil-6\"/>"
	+ "      <itemref idref=\"smil-7\"/>"
	+ "      <itemref idref=\"smil-8\"/>"
	+ "      <itemref idref=\"smil-9\"/>"
	+ "      <itemref idref=\"smil-10\"/>"
	+ "      <itemref idref=\"smil-11\"/>"
	+ "      <itemref idref=\"smil-12\"/>"
	+ "      <itemref idref=\"smil-13\"/>"
	+ "      <itemref idref=\"smil-14\"/>"
	+ "      <itemref idref=\"smil-15\"/>"
	+ "      <itemref idref=\"smil-16\"/>"
	+ "      <itemref idref=\"smil-17\"/>"
	+ "      <itemref idref=\"smil-18\"/>"
	+ "      <itemref idref=\"smil-19\"/>"
	+ "      <itemref idref=\"smil-20\"/>"
	+ "      <itemref idref=\"smil-21\"/>"
	+ "      <itemref idref=\"smil-22\"/>"
	+ "      <itemref idref=\"smil-23\"/>"
	+ "      <itemref idref=\"smil-24\"/>"
	+ "      <itemref idref=\"smil-25\"/>"
	+ "      <itemref idref=\"smil-26\"/>"
	+ "      <itemref idref=\"smil-27\"/>"
	+ "      <itemref idref=\"smil-28\"/>"
	+ "      <itemref idref=\"smil-29\"/>"
	+ "      <itemref idref=\"smil-30\"/>"
	+ "      <itemref idref=\"smil-31\"/>"
	+ "      <itemref idref=\"smil-32\"/>"
	+ "      <itemref idref=\"smil-33\"/>"
	+ "      <itemref idref=\"smil-34\"/>"
	+ "   </spine>"
	+ ""
	+ "</package>";

	private final String SPEECHGEN_NCX
	= "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
		+ "<!DOCTYPE ncx"
		+ "  PUBLIC \"-//NISO//DTD ncx 2005-1//EN\" \"http://www.daisy.org/z3986/2005/ncx-2005-1.dtd\">"
		+ "<ncx xmlns=\"http://www.daisy.org/z3986/2005/ncx/\" version=\"2005-1\" xml:lang=\"en-IN\">"
		+ "	  <head>"
		+ "		    <meta content=\"AUTO-UID-4767990567747899000\" name=\"dtb:uid\"/>"
		+ "		    <meta content=\"3\" name=\"dtb:depth\"/>"
		+ "		"
		+ "		    <meta content=\"TPB Narrator\" name=\"dtb:generator\"/>"
		+ "		    <meta content=\"20\" name=\"dtb:totalPageCount\"/>"
		+ "		    <meta content=\"20\" name=\"dtb:maxPageNumber\"/>"
		+ "	     <smilCustomTest bookStruct=\"PAGE_NUMBER\" defaultState=\"false\" id=\"pagenum\" override=\"visible\"/>"
		+ "   </head>"
		+ "  "
		+ "	  <docTitle>"
		+ "	     <text>ARE YOU READY?</text>"
		+ "      <audio clipBegin=\"0:00:00\" clipEnd=\"0:00:02.029\" src=\"speechgen0001.mp3\"/>"
		+ "   </docTitle>"
		+ "  "
		+ "	  <docAuthor>"
		+ "	     <text>WikiHow</text>"
		+ "      <audio clipBegin=\"0:00:02.029\" clipEnd=\"0:00:04.878\" src=\"speechgen0001.mp3\"/>"
		+ "   </docAuthor>"
		+ "	"
		+ "	  <navMap id=\"navMap\">"
		+ "      <navPoint class=\"h1\" id=\"ncx-1\" playOrder=\"1\">"
		+ "         <navLabel>"
		+ "            <text>A SHORT MANUAL ON DISASTER PREPAREDNESS"
		+ "</text>"
		+ "            <audio clipBegin=\"0:00:00\" clipEnd=\"0:00:05.939\" src=\"speechgen0002.mp3\"/>"
		+ "         </navLabel>"
		+ "         <content src=\"speechgen0002.smil#tcp3\"/>"
		+ "         <navPoint class=\"h2\" id=\"ncx-3\" playOrder=\"3\">"
		+ "            <navLabel>"
		+ "               <text>CONTENTS"
		+ "</text>"
		+ "               <audio clipBegin=\"0:00:00\" clipEnd=\"0:00:04.065\" src=\"speechgen0003.mp3\"/>"
		+ "            </navLabel>"
		+ "            <content src=\"speechgen0003.smil#tcp13\"/>"
		+ "         </navPoint>"
		+ "         <navPoint class=\"h2\" id=\"ncx-5\" playOrder=\"5\">"
		+ "            <navLabel>"
		+ "               <text>1. How to Make a Disaster Plan for Your Family</text>"
		+ "               <audio clipBegin=\"0:00:00\" clipEnd=\"0:00:04.624\" src=\"speechgen0004.mp3\"/>"
		+ "            </navLabel>"
		+ "            <content src=\"speechgen0004.smil#tcp31\"/>"
		+ "            <navPoint class=\"h3\" id=\"ncx-6\" playOrder=\"6\">"
		+ "               <navLabel>"
		+ "                  <text>Steps"
		+ "</text>"
		+ "                  <audio clipBegin=\"0:00:00\" clipEnd=\"0:00:03.911\" src=\"speechgen0005.mp3\"/>"
		+ "               </navLabel>"
		+ "               <content src=\"speechgen0005.smil#tcp36\"/>"
		+ "            </navPoint>"
		+ "            <navPoint class=\"h3\" id=\"ncx-8\" playOrder=\"8\">"
		+ "               <navLabel>"
		+ "                  <text>Tips"
		+ "</text>"
		+ "                  <audio clipBegin=\"0:00:00\" clipEnd=\"0:00:03.757\" src=\"speechgen0006.mp3\"/>"
		+ "               </navLabel>"
		+ "               <content src=\"speechgen0006.smil#tcp83\"/>"
		+ "            </navPoint>"
		+ "            <navPoint class=\"h3\" id=\"ncx-10\" playOrder=\"10\">"
		+ "               <navLabel>"
		+ "                  <text>Warnings"
		+ "</text>"
		+ "                  <audio clipBegin=\"0:00:00\" clipEnd=\"0:00:03.940\" src=\"speechgen0007.mp3\"/>"
		+ "               </navLabel>"
		+ "               <content src=\"speechgen0007.smil#tcp101\"/>"
		+ "            </navPoint>"
		+ "         </navPoint>"
		+ "         <navPoint class=\"h2\" id=\"ncx-12\" playOrder=\"12\">"
		+ "            <navLabel>"
		+ "               <text>2. How to Create a Home First Aid Kit</text>"
		+ "               <audio clipBegin=\"0:00:00\" clipEnd=\"0:00:03.999\" src=\"speechgen0008.mp3\"/>"
		+ "            </navLabel>"
		+ "            <content src=\"speechgen0008.smil#tcp105\"/>"
		+ "            <navPoint class=\"h3\" id=\"ncx-13\" playOrder=\"13\">"
		+ "               <navLabel>"
		+ "                  <text>Steps"
		+ "</text>"
		+ "                  <audio clipBegin=\"0:00:00\" clipEnd=\"0:00:03.911\" src=\"speechgen0009.mp3\"/>"
		+ "               </navLabel>"
		+ "               <content src=\"speechgen0009.smil#tcp110\"/>"
		+ "            </navPoint>"
		+ "            <navPoint class=\"h3\" id=\"ncx-15\" playOrder=\"15\">"
		+ "               <navLabel>"
		+ "                  <text>Tips"
		+ "</text>"
		+ "                  <audio clipBegin=\"0:00:00\" clipEnd=\"0:00:03.757\" src=\"speechgen0010.mp3\"/>"
		+ "               </navLabel>"
		+ "               <content src=\"speechgen0010.smil#tcp140\"/>"
		+ "            </navPoint>"
		+ "            <navPoint class=\"h3\" id=\"ncx-17\" playOrder=\"17\">"
		+ "               <navLabel>"
		+ "                  <text>Warnings"
		+ "</text>"
		+ "                  <audio clipBegin=\"0:00:00\" clipEnd=\"0:00:03.940\" src=\"speechgen0011.mp3\"/>"
		+ "               </navLabel>"
		+ "               <content src=\"speechgen0011.smil#tcp150\"/>"
		+ "            </navPoint>"
		+ "         </navPoint>"
		+ "         <navPoint class=\"h2\" id=\"ncx-19\" playOrder=\"19\">"
		+ "            <navLabel>"
		+ "               <text>3. How to Administer Adult CPR (Cardiopulmonary Resuscitation)</text>"
		+ "               <audio clipBegin=\"0:00:00\" clipEnd=\"0:00:06.982\" src=\"speechgen0012.mp3\"/>"
		+ "            </navLabel>"
		+ "            <content src=\"speechgen0012.smil#tcp157\"/>"
		+ "            <navPoint class=\"h3\" id=\"ncx-20\" playOrder=\"20\">"
		+ "               <navLabel>"
		+ "                  <text>Steps"
		+ "</text>"
		+ "                  <audio clipBegin=\"0:00:00\" clipEnd=\"0:00:03.918\" src=\"speechgen0013.mp3\"/>"
		+ "               </navLabel>"
		+ "               <content src=\"speechgen0013.smil#tcp166\"/>"
		+ "            </navPoint>"
		+ "            <navPoint class=\"h3\" id=\"ncx-22\" playOrder=\"22\">"
		+ "               <navLabel>"
		+ "                  <text>Tips"
		+ "</text>"
		+ "                  <audio clipBegin=\"0:00:00\" clipEnd=\"0:00:03.757\" src=\"speechgen0014.mp3\"/>"
		+ "               </navLabel>"
		+ "               <content src=\"speechgen0014.smil#tcp215\"/>"
		+ "            </navPoint>"
		+ "            <navPoint class=\"h3\" id=\"ncx-23\" playOrder=\"23\">"
		+ "               <navLabel>"
		+ "                  <text>Warnings"
		+ "</text>"
		+ "                  <audio clipBegin=\"0:00:00\" clipEnd=\"0:00:03.940\" src=\"speechgen0015.mp3\"/>"
		+ "               </navLabel>"
		+ "               <content src=\"speechgen0015.smil#tcp224\"/>"
		+ "            </navPoint>"
		+ "         </navPoint>"
		+ "         <navPoint class=\"h2\" id=\"ncx-25\" playOrder=\"25\">"
		+ "            <navLabel>"
		+ "               <text>4. How to Pack an Emergency Kit for the House</text>"
		+ "               <audio clipBegin=\"0:00:00\" clipEnd=\"0:00:04.676\" src=\"speechgen0016.mp3\"/>"
		+ "            </navLabel>"
		+ "            <content src=\"speechgen0016.smil#tcp236\"/>"
		+ "            <navPoint class=\"h3\" id=\"ncx-26\" playOrder=\"26\">"
		+ "               <navLabel>"
		+ "                  <text>Steps</text>"
		+ "                  <audio clipBegin=\"0:00:00\" clipEnd=\"0:00:03.911\" src=\"speechgen0017.mp3\"/>"
		+ "               </navLabel>"
		+ "               <content src=\"speechgen0017.smil#tcp242\"/>"
		+ "            </navPoint>"
		+ "            <navPoint class=\"h3\" id=\"ncx-29\" playOrder=\"29\">"
		+ "               <navLabel>"
		+ "                  <text>Tips"
		+ "</text>"
		+ "                  <audio clipBegin=\"0:00:00\" clipEnd=\"0:00:03.764\" src=\"speechgen0018.mp3\"/>"
		+ "               </navLabel>"
		+ "               <content src=\"speechgen0018.smil#tcp316\"/>"
		+ "            </navPoint>"
		+ "            <navPoint class=\"h3\" id=\"ncx-32\" playOrder=\"32\">"
		+ "               <navLabel>"
		+ "                  <text>Warnings"
		+ "</text>"
		+ "                  <audio clipBegin=\"0:00:00\" clipEnd=\"0:00:03.933\" src=\"speechgen0019.mp3\"/>"
		+ "               </navLabel>"
		+ "               <content src=\"speechgen0019.smil#tcp358\"/>"
		+ "            </navPoint>"
		+ "            <navPoint class=\"h3\" id=\"ncx-33\" playOrder=\"33\">"
		+ "               <navLabel>"
		+ "                  <text>Things You'll Need"
		+ "</text>"
		+ "                  <audio clipBegin=\"0:00:00\" clipEnd=\"0:00:04.359\" src=\"speechgen0020.mp3\"/>"
		+ "               </navLabel>"
		+ "               <content src=\"speechgen0020.smil#tcp363\"/>"
		+ "            </navPoint>"
		+ "            <navPoint class=\"h3\" id=\"ncx-35\" playOrder=\"35\">"
		+ "               <navLabel>"
		+ "                  <text>Other Items to Consider"
		+ "</text>"
		+ "                  <audio clipBegin=\"0:00:00\" clipEnd=\"0:00:04.734\" src=\"speechgen0021.mp3\"/>"
		+ "               </navLabel>"
		+ "               <content src=\"speechgen0021.smil#tcp393\"/>"
		+ "            </navPoint>"
		+ "         </navPoint>"
		+ "         <navPoint class=\"h2\" id=\"ncx-37\" playOrder=\"37\">"
		+ "            <navLabel>"
		+ "               <text>5. How to Avoid Danger During Civil Unrest</text>"
		+ "               <audio clipBegin=\"0:00:00\" clipEnd=\"0:00:04.631\" src=\"speechgen0022.mp3\"/>"
		+ "            </navLabel>"
		+ "            <content src=\"speechgen0022.smil#tcp406\"/>"
		+ "            <navPoint class=\"h3\" id=\"ncx-38\" playOrder=\"38\">"
		+ "               <navLabel>"
		+ "                  <text>Steps"
		+ "</text>"
		+ "                  <audio clipBegin=\"0:00:00\" clipEnd=\"0:00:03.918\" src=\"speechgen0023.mp3\"/>"
		+ "               </navLabel>"
		+ "               <content src=\"speechgen0023.smil#tcp411\"/>"
		+ "            </navPoint>"
		+ "            <navPoint class=\"h3\" id=\"ncx-40\" playOrder=\"40\">"
		+ "               <navLabel>"
		+ "                  <text>Tips"
		+ "</text>"
		+ "                  <audio clipBegin=\"0:00:00\" clipEnd=\"0:00:03.757\" src=\"speechgen0024.mp3\"/>"
		+ "               </navLabel>"
		+ "               <content src=\"speechgen0024.smil#tcp437\"/>"
		+ "            </navPoint>"
		+ "            <navPoint class=\"h3\" id=\"ncx-41\" playOrder=\"41\">"
		+ "               <navLabel>"
		+ "                  <text>Warnings"
		+ "</text>"
		+ "                  <audio clipBegin=\"0:00:00\" clipEnd=\"0:00:03.940\" src=\"speechgen0025.mp3\"/>"
		+ "               </navLabel>"
		+ "               <content src=\"speechgen0025.smil#tcp447\"/>"
		+ "            </navPoint>"
		+ "         </navPoint>"
		+ "         <navPoint class=\"h2\" id=\"ncx-43\" playOrder=\"43\">"
		+ "            <navLabel>"
		+ "               <text>6. How to Be Safe During a Landslide</text>"
		+ "               <audio clipBegin=\"0:00:00\" clipEnd=\"0:00:04.322\" src=\"speechgen0026.mp3\"/>"
		+ "            </navLabel>"
		+ "            <content src=\"speechgen0026.smil#tcp453\"/>"
		+ "            <navPoint class=\"h3\" id=\"ncx-44\" playOrder=\"44\">"
		+ "               <navLabel>"
		+ "                  <text>Steps"
		+ "</text>"
		+ "                  <audio clipBegin=\"0:00:00\" clipEnd=\"0:00:03.918\" src=\"speechgen0027.mp3\"/>"
		+ "               </navLabel>"
		+ "               <content src=\"speechgen0027.smil#tcp458\"/>"
		+ "            </navPoint>"
		+ "            <navPoint class=\"h3\" id=\"ncx-45\" playOrder=\"45\">"
		+ "               <navLabel>"
		+ "                  <text>Tips"
		+ "</text>"
		+ "                  <audio clipBegin=\"0:00:00\" clipEnd=\"0:00:03.757\" src=\"speechgen0028.mp3\"/>"
		+ "               </navLabel>"
		+ "               <content src=\"speechgen0028.smil#tcp477\"/>"
		+ "            </navPoint>"
		+ "            <navPoint class=\"h3\" id=\"ncx-46\" playOrder=\"46\">"
		+ "               <navLabel>"
		+ "                  <text>Warnings"
		+ "</text>"
		+ "                  <audio clipBegin=\"0:00:00\" clipEnd=\"0:00:03.933\" src=\"speechgen0029.mp3\"/>"
		+ "               </navLabel>"
		+ "               <content src=\"speechgen0029.smil#tcp481\"/>"
		+ "            </navPoint>"
		+ "         </navPoint>"
		+ "         <navPoint class=\"h2\" id=\"ncx-48\" playOrder=\"48\">"
		+ "            <navLabel>"
		+ "               <text>7. How to React During an Earthquake</text>"
		+ "               <audio clipBegin=\"0:00:00\" clipEnd=\"0:00:04.220\" src=\"speechgen0030.mp3\"/>"
		+ "            </navLabel>"
		+ "            <content src=\"speechgen0030.smil#tcp485\"/>"
		+ "            <navPoint class=\"h3\" id=\"ncx-49\" playOrder=\"49\">"
		+ "               <navLabel>"
		+ "                  <text>Steps"
		+ "</text>"
		+ "                  <audio clipBegin=\"0:00:00\" clipEnd=\"0:00:03.918\" src=\"speechgen0031.mp3\"/>"
		+ "               </navLabel>"
		+ "               <content src=\"speechgen0031.smil#tcp490\"/>"
		+ "            </navPoint>"
		+ "            <navPoint class=\"h3\" id=\"ncx-51\" playOrder=\"51\">"
		+ "               <navLabel>"
		+ "                  <text>Tips"
		+ "</text>"
		+ "                  <audio clipBegin=\"0:00:00\" clipEnd=\"0:00:03.764\" src=\"speechgen0032.mp3\"/>"
		+ "               </navLabel>"
		+ "               <content src=\"speechgen0032.smil#tcp534\"/>"
		+ "            </navPoint>"
		+ "            <navPoint class=\"h3\" id=\"ncx-52\" playOrder=\"52\">"
		+ "               <navLabel>"
		+ "                  <text>Warnings"
		+ "</text>"
		+ "                  <audio clipBegin=\"0:00:00\" clipEnd=\"0:00:03.933\" src=\"speechgen0033.mp3\"/>"
		+ "               </navLabel>"
		+ "               <content src=\"speechgen0033.smil#tcp557\"/>"
		+ "            </navPoint>"
		+ "            <navPoint class=\"h3\" id=\"ncx-53\" playOrder=\"53\">"
		+ "               <navLabel>"
		+ "                  <text>Things You'll Need"
		+ "</text>"
		+ "                  <audio clipBegin=\"0:00:00\" clipEnd=\"0:00:04.367\" src=\"speechgen0034.mp3\"/>"
		+ "               </navLabel>"
		+ "               <content src=\"speechgen0034.smil#tcp563\"/>"
		+ "            </navPoint>"
		+ "         </navPoint>"
		+ "      </navPoint>"
		+ "   </navMap>"
		+ "	"
		+ "	  <pageList id=\"page\">"
		+ "      <pageTarget class=\"pagenum\" id=\"ncx-2\" playOrder=\"2\" type=\"normal\" value=\"1\">"
		+ "         <navLabel>"
		+ "            <text>1</text>"
		+ "            <audio clipBegin=\"0:00:34.218\" clipEnd=\"0:00:35.388\" src=\"speechgen0002.mp3\"/>"
		+ "         </navLabel>"
		+ "         <content src=\"speechgen0002.smil#tcp12\"/>"
		+ "      </pageTarget>"
		+ "      <pageTarget class=\"pagenum\" id=\"ncx-4\" playOrder=\"4\" type=\"normal\" value=\"2\">"
		+ "         <navLabel>"
		+ "            <text>2</text>"
		+ "            <audio clipBegin=\"0:00:43.751\" clipEnd=\"0:00:46.958\" src=\"speechgen0003.mp3\"/>"
		+ "         </navLabel>"
		+ "         <content src=\"speechgen0003.smil#tcp30\"/>"
		+ "      </pageTarget>"
		+ "      <pageTarget class=\"pagenum\" id=\"ncx-7\" playOrder=\"7\" type=\"normal\" value=\"3\">"
		+ "         <navLabel>"
		+ "            <text>3</text>"
		+ "            <audio clipBegin=\"0:02:43.650\" clipEnd=\"0:02:45.201\" src=\"speechgen0005.mp3\"/>"
		+ "         </navLabel>"
		+ "         <content src=\"speechgen0005.smil#tcp59\"/>"
		+ "      </pageTarget>"
		+ "      <pageTarget class=\"pagenum\" id=\"ncx-9\" playOrder=\"9\" type=\"normal\" value=\"4\">"
		+ "         <navLabel>"
		+ "            <text>4</text>"
		+ "            <audio clipBegin=\"0:00:55.901\" clipEnd=\"0:00:57.152\" src=\"speechgen0006.mp3\"/>"
		+ "         </navLabel>"
		+ "         <content src=\"speechgen0006.smil#tcp90\"/>"
		+ "      </pageTarget>"
		+ "      <pageTarget class=\"pagenum\" id=\"ncx-11\" playOrder=\"11\" type=\"normal\" value=\"5\">"
		+ "         <navLabel>"
		+ "            <text>5</text>"
		+ "            <audio clipBegin=\"0:00:13.605\" clipEnd=\"0:00:16.988\" src=\"speechgen0007.mp3\"/>"
		+ "         </navLabel>"
		+ "         <content src=\"speechgen0007.smil#tcp104\"/>"
		+ "      </pageTarget>"
		+ "      <pageTarget class=\"pagenum\" id=\"ncx-14\" playOrder=\"14\" type=\"normal\" value=\"6\">"
		+ "         <navLabel>"
		+ "            <text>6</text>"
		+ "            <audio clipBegin=\"0:01:59.420\" clipEnd=\"0:02:00.715\" src=\"speechgen0009.mp3\"/>"
		+ "         </navLabel>"
		+ "         <content src=\"speechgen0009.smil#tcp135\"/>"
		+ "      </pageTarget>"
		+ "      <pageTarget class=\"pagenum\" id=\"ncx-16\" playOrder=\"16\" type=\"normal\" value=\"7\">"
		+ "         <navLabel>"
		+ "            <text>7</text>"
		+ "            <audio clipBegin=\"0:00:41.169\" clipEnd=\"0:00:42.464\" src=\"speechgen0010.mp3\"/>"
		+ "         </navLabel>"
		+ "         <content src=\"speechgen0010.smil#tcp149\"/>"
		+ "      </pageTarget>"
		+ "      <pageTarget class=\"pagenum\" id=\"ncx-18\" playOrder=\"18\" type=\"normal\" value=\"8\">"
		+ "         <navLabel>"
		+ "            <text>8</text>"
		+ "            <audio clipBegin=\"0:00:37.903\" clipEnd=\"0:00:41.051\" src=\"speechgen0011.mp3\"/>"
		+ "         </navLabel>"
		+ "         <content src=\"speechgen0011.smil#tcp156\"/>"
		+ "      </pageTarget>"
		+ "      <pageTarget class=\"pagenum\" id=\"ncx-21\" playOrder=\"21\" type=\"normal\" value=\"9\">"
		+ "         <navLabel>"
		+ "            <text>9</text>"
		+ "            <audio clipBegin=\"0:04:37.619\" clipEnd=\"0:04:38.980\" src=\"speechgen0013.mp3\"/>"
		+ "         </navLabel>"
		+ "         <content src=\"speechgen0013.smil#tcp214\"/>"
		+ "      </pageTarget>"
		+ "      <pageTarget class=\"pagenum\" id=\"ncx-24\" playOrder=\"24\" type=\"normal\" value=\"10\">"
		+ "         <navLabel>"
		+ "            <text>10</text>"
		+ "            <audio clipBegin=\"0:01:09.357\" clipEnd=\"0:01:12.630\" src=\"speechgen0015.mp3\"/>"
		+ "         </navLabel>"
		+ "         <content src=\"speechgen0015.smil#tcp235\"/>"
		+ "      </pageTarget>"
		+ "      <pageTarget class=\"pagenum\" id=\"ncx-27\" playOrder=\"27\" type=\"normal\" value=\"11\">"
		+ "         <navLabel>"
		+ "            <text>11</text>"
		+ "            <audio clipBegin=\"0:02:09.859\" clipEnd=\"0:02:11.461\" src=\"speechgen0017.mp3\"/>"
		+ "         </navLabel>"
		+ "         <content src=\"speechgen0017.smil#tcp265\"/>"
		+ "      </pageTarget>"
		+ "      <pageTarget class=\"pagenum\" id=\"ncx-28\" playOrder=\"28\" type=\"normal\" value=\"12\">"
		+ "         <navLabel>"
		+ "            <text>12</text>"
		+ "            <audio clipBegin=\"0:04:15.007\" clipEnd=\"0:04:16.683\" src=\"speechgen0017.mp3\"/>"
		+ "         </navLabel>"
		+ "         <content src=\"speechgen0017.smil#tcp293\"/>"
		+ "      </pageTarget>"
		+ "      <pageTarget class=\"pagenum\" id=\"ncx-30\" playOrder=\"30\" type=\"normal\" value=\"13\">"
		+ "         <navLabel>"
		+ "            <text>13</text>"
		+ "            <audio clipBegin=\"0:00:56.012\" clipEnd=\"0:00:57.879\" src=\"speechgen0018.mp3\"/>"
		+ "         </navLabel>"
		+ "         <content src=\"speechgen0018.smil#tcp327\"/>"
		+ "      </pageTarget>"
		+ "      <pageTarget class=\"pagenum\" id=\"ncx-31\" playOrder=\"31\" type=\"normal\" value=\"14\">"
		+ "         <navLabel>"
		+ "            <text>14</text>"
		+ "            <audio clipBegin=\"0:03:21.256\" clipEnd=\"0:03:22.823\" src=\"speechgen0018.mp3\"/>"
		+ "         </navLabel>"
		+ "         <content src=\"speechgen0018.smil#tcp357\"/>"
		+ "      </pageTarget>"
		+ "      <pageTarget class=\"pagenum\" id=\"ncx-34\" playOrder=\"34\" type=\"normal\" value=\"15\">"
		+ "         <navLabel>"
		+ "            <text>15</text>"
		+ "            <audio clipBegin=\"0:03:03.559\" clipEnd=\"0:03:05.045\" src=\"speechgen0020.mp3\"/>"
		+ "         </navLabel>"
		+ "         <content src=\"speechgen0020.smil#tcp392\"/>"
		+ "      </pageTarget>"
		+ "      <pageTarget class=\"pagenum\" id=\"ncx-36\" playOrder=\"36\" type=\"normal\" value=\"16\">"
		+ "         <navLabel>"
		+ "            <text>16</text>"
		+ "            <audio clipBegin=\"0:01:10.259\" clipEnd=\"0:01:13.870\" src=\"speechgen0021.mp3\"/>"
		+ "         </navLabel>"
		+ "         <content src=\"speechgen0021.smil#tcp405\"/>"
		+ "      </pageTarget>"
		+ "      <pageTarget class=\"pagenum\" id=\"ncx-39\" playOrder=\"39\" type=\"normal\" value=\"17\">"
		+ "         <navLabel>"
		+ "            <text>17</text>"
		+ "            <audio clipBegin=\"0:02:58.397\" clipEnd=\"0:03:00.059\" src=\"speechgen0023.mp3\"/>"
		+ "         </navLabel>"
		+ "         <content src=\"speechgen0023.smil#tcp436\"/>"
		+ "      </pageTarget>"
		+ "      <pageTarget class=\"pagenum\" id=\"ncx-42\" playOrder=\"42\" type=\"normal\" value=\"18\">"
		+ "         <navLabel>"
		+ "            <text>18</text>"
		+ "            <audio clipBegin=\"0:00:28.213\" clipEnd=\"0:00:31.647\" src=\"speechgen0025.mp3\"/>"
		+ "         </navLabel>"
		+ "         <content src=\"speechgen0025.smil#tcp452\"/>"
		+ "      </pageTarget>"
		+ "      <pageTarget class=\"pagenum\" id=\"ncx-47\" playOrder=\"47\" type=\"normal\" value=\"19\">"
		+ "         <navLabel>"
		+ "            <text>19</text>"
		+ "            <audio clipBegin=\"0:00:11.357\" clipEnd=\"0:00:14.894\" src=\"speechgen0029.mp3\"/>"
		+ "         </navLabel>"
		+ "         <content src=\"speechgen0029.smil#tcp484\"/>"
		+ "      </pageTarget>"
		+ "      <pageTarget class=\"pagenum\" id=\"ncx-50\" playOrder=\"50\" type=\"normal\" value=\"20\">"
		+ "         <navLabel>"
		+ "            <text>20</text>"
		+ "            <audio clipBegin=\"0:03:38.131\" clipEnd=\"0:03:39.396\" src=\"speechgen0031.mp3\"/>"
		+ "         </navLabel>"
		+ "         <content src=\"speechgen0031.smil#tcp533\"/>"
		+ "      </pageTarget>"
		+ "   </pageList>"
		+ "  "
		+ "</ncx>";
	
	private final String SPEECHGEN0002_SMIL
		= "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
		+ "<!DOCTYPE smil"
		+ "  PUBLIC \"-//NISO//DTD dtbsmil 2005-2//EN\" \"http://www.daisy.org/z3986/2005/dtbsmil-2005-2.dtd\">"
		+ "<smil xmlns=\"http://www.w3.org/2001/SMIL20/\">"
		+ "	  <head>"
		+ "		    <meta content=\"AUTO-UID-4767990567747899000\" name=\"dtb:uid\"/>"
		+ "		    <meta content=\"TPB Narrator\" name=\"dtb:generator\"/>"
		+ "		    <meta content=\"0:00:04.878\" name=\"dtb:totalElapsedTime\"/>"
		+ "		    <customAttributes>"
		+ "		       <customTest defaultState=\"false\" id=\"pagenum\" override=\"visible\"/>"
		+ "      </customAttributes>"
		+ "	  </head>"
		+ "	  <body>"
		+ "		    <seq dur=\"0:00:35.388\" fill=\"remove\" id=\"mseq\">"
		+ "		       <par id=\"tcp3\">"
		+ "            <text id=\"text3\" src=\"AreYouReadyV3.xml#dtb3\"/>"
		+ "            <audio clipBegin=\"0:00:00\" clipEnd=\"0:00:05.939\" src=\"speechgen0002.mp3\"/>"
		+ "         </par>"
		+ "         <seq class=\"blockquote\" end=\"DTBuserEscape;tcp6.end\" fill=\"remove\" id=\"tcs1\">"
		+ "            <par id=\"tcp4\">"
		+ "               <text id=\"text4\" src=\"AreYouReadyV3.xml#dtb5\"/>"
		+ "               <audio clipBegin=\"0:00:05.939\" clipEnd=\"0:00:13.931\" src=\"speechgen0002.mp3\"/>"
		+ "            </par>"
		+ "            <par id=\"tcp5\">"
		+ "               <text id=\"text5\" src=\"AreYouReadyV3.xml#dtb6\"/>"
		+ "               <audio clipBegin=\"0:00:13.931\" clipEnd=\"0:00:18.363\" src=\"speechgen0002.mp3\"/>"
		+ "            </par>"
		+ "            <par id=\"tcp6\">"
		+ "               <text id=\"text6\" src=\"AreYouReadyV3.xml#dtb7\"/>"
		+ "               <audio clipBegin=\"0:00:18.363\" clipEnd=\"0:00:24.247\" src=\"speechgen0002.mp3\"/>"
		+ "            </par>"
		+ "         </seq>"
		+ "         <par id=\"tcp7\">"
		+ "            <text id=\"text7\" src=\"AreYouReadyV3.xml#rId51\"/>"
		+ "            <audio clipBegin=\"0:00:24.247\" clipEnd=\"0:00:25.703\" src=\"speechgen0002.mp3\"/>"
		+ "         </par>"
		+ "         <par id=\"tcp8\">"
		+ "            <text id=\"text8\" src=\"AreYouReadyV3.xml#rId62\"/>"
		+ "            <audio clipBegin=\"0:00:25.703\" clipEnd=\"0:00:27.571\" src=\"speechgen0002.mp3\"/>"
		+ "         </par>"
		+ "         <par id=\"tcp9\">"
		+ "            <text id=\"text9\" src=\"AreYouReadyV3.xml#dtb8\"/>"
		+ "            <audio clipBegin=\"0:00:27.571\" clipEnd=\"0:00:29.064\" src=\"speechgen0002.mp3\"/>"
		+ "         </par>"
		+ "         <par id=\"tcp10\">"
		+ "            <text id=\"text10\" src=\"AreYouReadyV3.xml#dtb9\"/>"
		+ "            <audio clipBegin=\"0:00:29.064\" clipEnd=\"0:00:30.844\" src=\"speechgen0002.mp3\"/>"
		+ "         </par>"
		+ "         <par id=\"tcp11\">"
		+ "            <text id=\"text11\" src=\"AreYouReadyV3.xml#dtb10\"/>"
		+ "            <audio clipBegin=\"0:00:30.844\" clipEnd=\"0:00:34.218\" src=\"speechgen0002.mp3\"/>"
		+ "         </par>"
		+ "         <par customTest=\"pagenum\" id=\"tcp12\">"
		+ "            <text id=\"text12\" src=\"AreYouReadyV3.xml#page1\"/>"
		+ "            <audio clipBegin=\"0:00:34.218\" clipEnd=\"0:00:35.388\" src=\"speechgen0002.mp3\"/>"
		+ "         </par>"
		+ "      </seq>"
		+ "	  </body>"
		+ "</smil>";
	
	private final String SPEECHGEN0003_SMIL
		= "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
		+ "<!DOCTYPE smil"
		+ "  PUBLIC \"-//NISO//DTD dtbsmil 2005-2//EN\" \"http://www.daisy.org/z3986/2005/dtbsmil-2005-2.dtd\">"
		+ "<smil xmlns=\"http://www.w3.org/2001/SMIL20/\">"
		+ "	  <head>"
		+ "		    <meta content=\"AUTO-UID-4767990567747899000\" name=\"dtb:uid\"/>"
		+ "		    <meta content=\"TPB Narrator\" name=\"dtb:generator\"/>"
		+ "		    <meta content=\"0:00:40.266\" name=\"dtb:totalElapsedTime\"/>"
		+ "		    <customAttributes>"
		+ "		       <customTest defaultState=\"false\" id=\"pagenum\" override=\"visible\"/>"
		+ "      </customAttributes>"
		+ "	  </head>"
		+ "	  <body>"
		+ "		    <seq dur=\"0:00:46.958\" fill=\"remove\" id=\"mseq\">"
		+ "		       <par id=\"tcp13\">"
		+ "            <text id=\"text13\" src=\"AreYouReadyV3.xml#dtb11\"/>"
		+ "            <audio clipBegin=\"0:00:00\" clipEnd=\"0:00:04.065\" src=\"speechgen0003.mp3\"/>"
		+ "         </par>"
		+ "         <seq class=\"table\" end=\"DTBuserEscape;tcs10.end\" fill=\"remove\" id=\"tcs2\">"
		+ "            <seq class=\"tr\" end=\"DTBuserEscape;tcp15.end\" fill=\"remove\" id=\"tcs3\">"
		+ "               <par id=\"tcp14\">"
		+ "                  <text id=\"text14\" src=\"AreYouReadyV3.xml#dtb14\"/>"
		+ "                  <audio clipBegin=\"0:00:04.065\" clipEnd=\"0:00:06.576\" src=\"speechgen0003.mp3\"/>"
		+ "               </par>"
		+ "               <par id=\"tcp15\">"
		+ "                  <text id=\"text15\" src=\"AreYouReadyV3.xml#dtb15\"/>"
		+ "                  <audio clipBegin=\"0:00:06.576\" clipEnd=\"0:00:07.628\" src=\"speechgen0003.mp3\"/>"
		+ "               </par>"
		+ "            </seq>"
		+ "            <seq class=\"tr\" end=\"DTBuserEscape;tcp17.end\" fill=\"remove\" id=\"tcs4\">"
		+ "               <par id=\"tcp16\">"
		+ "                  <text id=\"text16\" src=\"AreYouReadyV3.xml#dtb17\"/>"
		+ "                  <audio clipBegin=\"0:00:07.628\" clipEnd=\"0:00:11.259\" src=\"speechgen0003.mp3\"/>"
		+ "               </par>"
		+ "               <par id=\"tcp17\">"
		+ "                  <text id=\"text17\" src=\"AreYouReadyV3.xml#dtb18\"/>"
		+ "                  <audio clipBegin=\"0:00:11.259\" clipEnd=\"0:00:12.289\" src=\"speechgen0003.mp3\"/>"
		+ "               </par>"
		+ "            </seq>"
		+ "            <seq class=\"tr\" end=\"DTBuserEscape;tcp19.end\" fill=\"remove\" id=\"tcs5\">"
		+ "               <par id=\"tcp18\">"
		+ "                  <text id=\"text18\" src=\"AreYouReadyV3.xml#dtb20\"/>"
		+ "                  <audio clipBegin=\"0:00:12.289\" clipEnd=\"0:00:15.288\" src=\"speechgen0003.mp3\"/>"
		+ "               </par>"
		+ "               <par id=\"tcp19\">"
		+ "                  <text id=\"text19\" src=\"AreYouReadyV3.xml#dtb21\"/>"
		+ "                  <audio clipBegin=\"0:00:15.288\" clipEnd=\"0:00:16.377\" src=\"speechgen0003.mp3\"/>"
		+ "               </par>"
		+ "            </seq>"
		+ "            <seq class=\"tr\" end=\"DTBuserEscape;tcp21.end\" fill=\"remove\" id=\"tcs6\">"
		+ "               <par id=\"tcp20\">"
		+ "                  <text id=\"text20\" src=\"AreYouReadyV3.xml#dtb23\"/>"
		+ "                  <audio clipBegin=\"0:00:16.377\" clipEnd=\"0:00:22.359\" src=\"speechgen0003.mp3\"/>"
		+ "               </par>"
		+ "               <par id=\"tcp21\">"
		+ "                  <text id=\"text21\" src=\"AreYouReadyV3.xml#dtb24\"/>"
		+ "                  <audio clipBegin=\"0:00:22.359\" clipEnd=\"0:00:23.411\" src=\"speechgen0003.mp3\"/>"
		+ "               </par>"
		+ "            </seq>"
		+ "            <seq class=\"tr\" end=\"DTBuserEscape;tcp23.end\" fill=\"remove\" id=\"tcs7\">"
		+ "               <par id=\"tcp22\">"
		+ "                  <text id=\"text22\" src=\"AreYouReadyV3.xml#dtb26\"/>"
		+ "                  <audio clipBegin=\"0:00:23.411\" clipEnd=\"0:00:27.079\" src=\"speechgen0003.mp3\"/>"
		+ "               </par>"
		+ "               <par id=\"tcp23\">"
		+ "                  <text id=\"text23\" src=\"AreYouReadyV3.xml#dtb27\"/>"
		+ "                  <audio clipBegin=\"0:00:27.079\" clipEnd=\"0:00:28.102\" src=\"speechgen0003.mp3\"/>"
		+ "               </par>"
		+ "            </seq>"
		+ "            <seq class=\"tr\" end=\"DTBuserEscape;tcp25.end\" fill=\"remove\" id=\"tcs8\">"
		+ "               <par id=\"tcp24\">"
		+ "                  <text id=\"text24\" src=\"AreYouReadyV3.xml#dtb29\"/>"
		+ "                  <audio clipBegin=\"0:00:28.102\" clipEnd=\"0:00:31.733\" src=\"speechgen0003.mp3\"/>"
		+ "               </par>"
		+ "               <par id=\"tcp25\">"
		+ "                  <text id=\"text25\" src=\"AreYouReadyV3.xml#dtb30\"/>"
		+ "                  <audio clipBegin=\"0:00:31.733\" clipEnd=\"0:00:33.050\" src=\"speechgen0003.mp3\"/>"
		+ "               </par>"
		+ "            </seq>"
		+ "            <seq class=\"tr\" end=\"DTBuserEscape;tcp27.end\" fill=\"remove\" id=\"tcs9\">"
		+ "               <par id=\"tcp26\">"
		+ "                  <text id=\"text26\" src=\"AreYouReadyV3.xml#dtb32\"/>"
		+ "                  <audio clipBegin=\"0:00:33.050\" clipEnd=\"0:00:36.372\" src=\"speechgen0003.mp3\"/>"
		+ "               </par>"
		+ "               <par id=\"tcp27\">"
		+ "                  <text id=\"text27\" src=\"AreYouReadyV3.xml#dtb33\"/>"
		+ "                  <audio clipBegin=\"0:00:36.372\" clipEnd=\"0:00:37.542\" src=\"speechgen0003.mp3\"/>"
		+ "               </par>"
		+ "            </seq>"
		+ "            <seq class=\"tr\" end=\"DTBuserEscape;tcp29.end\" fill=\"remove\" id=\"tcs10\">"
		+ "               <par id=\"tcp28\">"
		+ "                  <text id=\"text28\" src=\"AreYouReadyV3.xml#dtb35\"/>"
		+ "                  <audio clipBegin=\"0:00:37.542\" clipEnd=\"0:00:40.769\" src=\"speechgen0003.mp3\"/>"
		+ "               </par>"
		+ "               <par id=\"tcp29\">"
		+ "                  <text id=\"text29\" src=\"AreYouReadyV3.xml#dtb36\"/>"
		+ "                  <audio clipBegin=\"0:00:40.769\" clipEnd=\"0:00:43.751\" src=\"speechgen0003.mp3\"/>"
		+ "               </par>"
		+ "            </seq>"
		+ "         </seq>"
		+ "         <par customTest=\"pagenum\" id=\"tcp30\">"
		+ "            <text id=\"text30\" src=\"AreYouReadyV3.xml#page2\"/>"
		+ "            <audio clipBegin=\"0:00:43.751\" clipEnd=\"0:00:46.958\" src=\"speechgen0003.mp3\"/>"
		+ "         </par>"
		+ "      </seq>"
		+ "	  </body>"
		+ "</smil>";

	private final String SPEECHGEN0007_SMIL
		= "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
		+ "<!DOCTYPE smil"
		+ "  PUBLIC \"-//NISO//DTD dtbsmil 2005-2//EN\" \"http://www.daisy.org/z3986/2005/dtbsmil-2005-2.dtd\">"
		+ "<smil xmlns=\"http://www.w3.org/2001/SMIL20/\">"
		+ "	  <head>"
		+ "		    <meta content=\"AUTO-UID-4767990567747899000\" name=\"dtb:uid\"/>"
		+ "		    <meta content=\"TPB Narrator\" name=\"dtb:generator\"/>"
		+ "		    <meta content=\"0:09:17.059\" name=\"dtb:totalElapsedTime\"/>"
		+ "		    <customAttributes>"
		+ "		       <customTest defaultState=\"false\" id=\"pagenum\" override=\"visible\"/>"
		+ "      </customAttributes>"
		+ "	  </head>"
		+ "	  <body>"
		+ "		    <seq dur=\"0:00:16.988\" fill=\"remove\" id=\"mseq\">"
		+ "		       <par id=\"tcp101\">"
		+ "            <text id=\"text101\" src=\"AreYouReadyV3.xml#dtb107\"/>"
		+ "            <audio clipBegin=\"0:00:00\" clipEnd=\"0:00:03.940\" src=\"speechgen0007.mp3\"/>"
		+ "         </par>"
		+ "         <par id=\"tcp102\">"
		+ "            <text id=\"text102\" src=\"AreYouReadyV3.xml#dtb108\"/>"
		+ "            <audio clipBegin=\"0:00:03.940\" clipEnd=\"0:00:08.137\" src=\"speechgen0007.mp3\"/>"
		+ "         </par>"
		+ "         <par id=\"tcp103\">"
		+ "            <text id=\"text103\" src=\"AreYouReadyV3.xml#dtb109\"/>"
		+ "            <audio clipBegin=\"0:00:08.137\" clipEnd=\"0:00:13.605\" src=\"speechgen0007.mp3\"/>"
		+ "         </par>"
		+ "         <par customTest=\"pagenum\" id=\"tcp104\">"
		+ "            <text id=\"text104\" src=\"AreYouReadyV3.xml#page5\"/>"
		+ "            <audio clipBegin=\"0:00:13.605\" clipEnd=\"0:00:16.988\" src=\"speechgen0007.mp3\"/>"
		+ "         </par>"
		+ "      </seq>"
		+ "	  </body>"
		+ "</smil>";
	
	public final String SPEECHGEN0008_SMIL
		= "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
		+ "<!DOCTYPE smil"
		+ "  PUBLIC \"-//NISO//DTD dtbsmil 2005-2//EN\" \"http://www.daisy.org/z3986/2005/dtbsmil-2005-2.dtd\">"
		+ "<smil xmlns=\"http://www.w3.org/2001/SMIL20/\">"
		+ "	  <head>"
		+ "		    <meta content=\"AUTO-UID-4767990567747899000\" name=\"dtb:uid\"/>"
		+ "		    <meta content=\"TPB Narrator\" name=\"dtb:generator\"/>"
		+ "		    <meta content=\"0:09:34.047\" name=\"dtb:totalElapsedTime\"/>"
		+ "		"
		+ "	  </head>"
		+ "	  <body>"
		+ "		    <seq dur=\"0:00:15.304\" fill=\"remove\" id=\"mseq\">"
		+ "		       <par id=\"tcp105\">"
		+ "            <text id=\"text105\" src=\"AreYouReadyV3.xml#dtb110\"/>"
		+ "            <audio clipBegin=\"0:00:00\" clipEnd=\"0:00:01.749\" src=\"speechgen0008.mp3\"/>"
		+ "         </par>"
		+ "         <par id=\"tcp106\">"
		+ "            <text id=\"text106\" src=\"AreYouReadyV3.xml#dtb111\"/>"
		+ "            <audio clipBegin=\"0:00:01.749\" clipEnd=\"0:00:03.999\" src=\"speechgen0008.mp3\"/>"
		+ "         </par>"
		+ "         <par id=\"tcp107\">"
		+ "            <text id=\"text107\" src=\"AreYouReadyV3.xml#rId83\"/>"
		+ "            <audio clipBegin=\"0:00:03.999\" clipEnd=\"0:00:06.418\" src=\"speechgen0008.mp3\"/>"
		+ "         </par>"
		+ "         <par id=\"tcp108\">"
		+ "            <text id=\"text108\" src=\"AreYouReadyV3.xml#dtb112\"/>"
		+ "            <audio clipBegin=\"0:00:06.418\" clipEnd=\"0:00:10.982\" src=\"speechgen0008.mp3\"/>"
		+ "         </par>"
		+ "         <par id=\"tcp109\">"
		+ "            <text id=\"text109\" src=\"AreYouReadyV3.xml#dtb113\"/>"
		+ "            <audio clipBegin=\"0:00:10.982\" clipEnd=\"0:00:15.304\" src=\"speechgen0008.mp3\"/>"
		+ "         </par>"
		+ "      </seq>"
		+ "	  </body>"
		+ "</smil>";
	
	public final String AREYOUREADYV3_XML
		= "<?xml version='1.0' encoding='utf-8'?><!DOCTYPE dtbook PUBLIC \"-//NISO//DTD dtbook 2005-3//EN\" \"http://www.daisy.org/z3986/2005/dtbook-2005-3.dtd\"><?xml-stylesheet href=\"dtbookbasic.css\" type=\"text/css\"?><dtbook xmlns=\"http://www.daisy.org/z3986/2005/dtbook/\" version=\"2005-3\" xml:lang=\"en-IN\">"
		+ "	<head>"
		+ "		<meta content=\"1.0\" name=\"dt:version\" />"
		+ "		<meta name=\"dtb:uid\" content=\"AUTO-UID-4767990567747899000\" />"
		+ "		<meta content=\"ARE YOU READY?\" name=\"dc:Title\" />"
		+ "		<meta content=\"WikiHow\" name=\"dc:Creator\" />"
		+ "		<meta content=\"2009-04-26\" name=\"dc:Date\" />"
		+ "		<meta content=\"DAISY India\" name=\"dc:Publisher\" />"
		+ "		<meta name=\"dc:Subject\" content=\"A Short Manual for Disaster Management\" />"
		+ "		<meta content=\"5078727220897727718\" name=\"dc:Identifier\" />"
		+ "		<meta name=\"dc:Language\" content=\"en-IN\" />"
		+ "	</head>"
		+ "	<book showin=\"blp\">"
		+ "		<frontmatter>"
		+ "			<doctitle id=\"dtb1\" smilref=\"speechgen0001.smil#tcp1\">ARE YOU READY?</doctitle>"
		+ "			<docauthor id=\"dtb2\" smilref=\"speechgen0001.smil#tcp2\">WikiHow</docauthor>"
		+ "		</frontmatter>"
		+ "		<bodymatter id=\"bodymatter_0001\">"
		+ "			<level1>"
		+ "				<h1 id=\"dtb3\" smilref=\"speechgen0002.smil#tcp3\">A SHORT MANUAL ON DISASTER PREPAREDNESS"
		+ "</h1>"
		+ "				<blockquote id=\"dtb4\" smilref=\"speechgen0002.smil#tcs1\"><p><sent id=\"dtb5\" smilref=\"speechgen0002.smil#tcp4\">\"Articles provided by wikiHow, a wiki building the world's largest, highest quality how-to manual. </sent><sent smilref=\"speechgen0002.smil#tcp5\" id=\"dtb6\">Please edit these article and find author credits at wikiHow.com. </sent><sent smilref=\"speechgen0002.smil#tcp6\" id=\"dtb7\">Content on wikiHow can be shared under a Creative Commons License.\"</sent></p></blockquote>"
		+ "				<p><img id=\"rId51\" src=\"image1.jpg\" alt=\"WikiHow Logo\" />"
		+ "				</p>"
		+ "				<p><imggroup><img smilref=\"speechgen0002.smil#tcp8\" alt=\"Creative Commons logo\" id=\"rId62\" src=\"image2.jpg\" /></imggroup>"
		+ "				</p>"
		+ "				<p smilref=\"speechgen0002.smil#tcp9\" id=\"dtb8\">Compiled by</p>"
		+ "				<author id=\"dtb9\" smilref=\"speechgen0002.smil#tcp10\" xml:lang=\"en-IN\">Prashant Ranjan Verma"
		+ "</author>"
		+ "				<p smilref=\"speechgen0002.smil#tcp11\" id=\"dtb10\">www.daisyindia.org</p>"
		+ "				<pagenum id=\"page1\" page=\"normal\" smilref=\"speechgen0002.smil#tcp12\">1</pagenum>"
		+ "				<level2>"
		+ "					<h2 id=\"dtb11\" smilref=\"speechgen0003.smil#tcp13\">CONTENTS"
		+ "</h2>"
		+ "					<table border=\"1\" id=\"dtb12\" smilref=\"speechgen0003.smil#tcs2\">"
		+ "						<col align=\"right\" span=\"1\" />"
		+ "						<tbody>"
		+ "							<tr id=\"dtb13\" smilref=\"speechgen0003.smil#tcs3\">"
		+ "								<td rowspan=\"1\" colspan=\"1\"><p id=\"dtb14\" smilref=\"speechgen0003.smil#tcp14\">Chapter</p></td>"
		+ "								<td colspan=\"1\" rowspan=\"1\"><p id=\"dtb15\" smilref=\"speechgen0003.smil#tcp15\">Page</p></td>"
		+ "							</tr>"
		+ "							<tr id=\"dtb16\" smilref=\"speechgen0003.smil#tcs4\">"
		+ "								<td colspan=\"1\" rowspan=\"1\"><p><sent><strong smilref=\"speechgen0003.smil#tcp16\" id=\"dtb17\">1. How to Make a Disaster Plan for Your Family</strong></sent></p>"
		+ "								</td>"
		+ "								<td rowspan=\"1\" colspan=\"1\"><p><strong id=\"dtb18\" smilref=\"speechgen0003.smil#tcp17\">3</strong></p>"
		+ "								</td>"
		+ "							</tr>"
		+ "							<tr id=\"dtb19\" smilref=\"speechgen0003.smil#tcs5\">"
		+ "								<td colspan=\"1\" rowspan=\"1\"><p><sent><strong id=\"dtb20\" smilref=\"speechgen0003.smil#tcp18\">2. How to Create a Home First Aid Kit</strong></sent></p>"
		+ "								</td>"
		+ "								<td colspan=\"1\" rowspan=\"1\"><p><strong id=\"dtb21\" smilref=\"speechgen0003.smil#tcp19\">6</strong></p>"
		+ "								</td>"
		+ "							</tr>"
		+ "							<tr id=\"dtb22\" smilref=\"speechgen0003.smil#tcs6\">"
		+ "								<td rowspan=\"1\" colspan=\"1\"><p><sent><strong id=\"dtb23\" smilref=\"speechgen0003.smil#tcp20\">3. How to Administer Adult CPR (Cardiopulmonary Resuscitation)</strong></sent></p>"
		+ "								</td>"
		+ "								<td rowspan=\"1\" colspan=\"1\"><p><strong id=\"dtb24\" smilref=\"speechgen0003.smil#tcp21\">9</strong></p>"
		+ "								</td>"
		+ "							</tr>"
		+ "							<tr smilref=\"speechgen0003.smil#tcs7\" id=\"dtb25\">"
		+ "								<td colspan=\"1\" rowspan=\"1\"><p><sent><strong smilref=\"speechgen0003.smil#tcp22\" id=\"dtb26\">4. How to Pack an Emergency Kit for the House</strong></sent></p>"
		+ "								</td>"
		+ "								<td rowspan=\"1\" colspan=\"1\"><p><strong smilref=\"speechgen0003.smil#tcp23\" id=\"dtb27\">11</strong></p>"
		+ "								</td>"
		+ "							</tr>"
		+ "							<tr smilref=\"speechgen0003.smil#tcs8\" id=\"dtb28\">"
		+ "								<td colspan=\"1\" rowspan=\"1\"><p><sent><strong smilref=\"speechgen0003.smil#tcp24\" id=\"dtb29\">5. How to Avoid Danger During Civil Unrest</strong></sent></p>"
		+ "								</td>"
		+ "								<td rowspan=\"1\" colspan=\"1\"><p><strong id=\"dtb30\" smilref=\"speechgen0003.smil#tcp25\">17</strong></p>"
		+ "								</td>"
		+ "							</tr>"
		+ "							<tr id=\"dtb31\" smilref=\"speechgen0003.smil#tcs9\">"
		+ "								<td colspan=\"1\" rowspan=\"1\"><p><sent><strong smilref=\"speechgen0003.smil#tcp26\" id=\"dtb32\">6. How to Be Safe During a Landslide</strong></sent></p>"
		+ "								</td>"
		+ "								<td rowspan=\"1\" colspan=\"1\"><p><strong id=\"dtb33\" smilref=\"speechgen0003.smil#tcp27\">18</strong></p>"
		+ "								</td>"
		+ "							</tr>"
		+ "							<tr id=\"dtb34\" smilref=\"speechgen0003.smil#tcs10\">"
		+ "								<td rowspan=\"1\" colspan=\"1\">"
		+ "									<p><sent><strong><em id=\"dtb35\" smilref=\"speechgen0003.smil#tcp28\">7. How to React During an Earthquake</em></strong>"
		+ "									</sent></p>"
		+ "								</td>"
		+ "								<td rowspan=\"1\" colspan=\"1\"><p><strong smilref=\"speechgen0003.smil#tcp29\" id=\"dtb36\">19</strong></p>"
		+ "								</td>"
		+ "							</tr>"
		+ "						</tbody>"
		+ "					</table>"
		+ "					<pagenum id=\"page2\" page=\"normal\" smilref=\"speechgen0003.smil#tcp30\">2</pagenum>"
		+ "				</level2>"
		+ "				<level2>"
		+ "					<h2><sent id=\"dtb37\" smilref=\"speechgen0004.smil#tcp31\">1. </sent><sent smilref=\"speechgen0004.smil#tcp32\" id=\"dtb38\">How to Make a Disaster Plan for Your Family"
		+ "</sent></h2>"
		+ "					<p><sent id=\"dtb39\" smilref=\"speechgen0004.smil#tcp33\">Disasters, whether natural (hurricanes, tornadoes, and floods, for example) or man-made (i.e. fires, nuclear accidents, or terrorist attacks) can strike at any time, whether we're ready for them or not. </sent><sent smilref=\"speechgen0004.smil#tcp34\" id=\"dtb40\">Even with advance warning, a disaster can be overwhelming, and it's not always possible to communicate with family members who may be at work or school when an emergency strikes. </sent><sent id=\"dtb41\" smilref=\"speechgen0004.smil#tcp35\">A little planning and practice <em>before</em> you're in danger can help you and your family survive even the worst disasters.</sent></p>"
		+ "					<level3>"
		+ "						<h3 smilref=\"speechgen0005.smil#tcp36\" id=\"dtb42\">Steps"
		+ "</h3>"
		+ "						<list id=\"dtb43\" type=\"ol\" smilref=\"speechgen0005.smil#tcs11\">"
		+ "							<li><p><sent smilref=\"speechgen0005.smil#tcp37\" id=\"dtb44\">Determine what disasters your area is susceptible to. </sent><sent smilref=\"speechgen0005.smil#tcp38\" id=\"dtb45\">If you live in Kansas, you don't need to prepare for a hurricane, but you'd better be ready for tornadoes. </sent><sent smilref=\"speechgen0005.smil#tcp39\" id=\"dtb46\">While some disasters, such as fire, can happen anywhere, the hazards you might encounter vary widely from place to place. </sent><sent id=\"dtb47\" smilref=\"speechgen0005.smil#tcp40\">Check with your local emergency management or civil defense office, Red Cross chapter, or the National Weather Service to get an idea of what emergencies you should prepare for. </sent></p></li>"
		+ "							<li><p><sent id=\"dtb48\" smilref=\"speechgen0005.smil#tcp41\">Find out what you should do in case a disaster strikes. </sent><sent id=\"dtb49\" smilref=\"speechgen0005.smil#tcp42\">The organizations above will likely be able to advise you what to do in an emergency. </sent><sent smilref=\"speechgen0005.smil#tcp43\" id=\"dtb50\">They may be able to provide you with evacuation maps and information about local warning systems and emergency plans. </sent><sent id=\"dtb51\" smilref=\"speechgen0005.smil#tcp44\">If you can't get all the information you need from officials, research your local hazards on your own. </sent><sent smilref=\"speechgen0005.smil#tcp45\" id=\"dtb52\">Figure out, for example, what preparations you should make for a tornado or hurricane (you can find information on many disaster situations right here on wikiHow) and how to survive if you're caught in a disaster, and determine the best evacuation routes on your own if need be. </sent><sent id=\"dtb53\" smilref=\"speechgen0005.smil#tcp46\">Remember, when push comes to shove, it's <em>your</em> responsibility to ensure your family is well prepared. </sent></p>"
		+ "							</li>"
		+ "							<li><p><sent id=\"dtb54\" smilref=\"speechgen0005.smil#tcp47\">Pick a meeting spot and a way to get in contact with your family members. </sent><sent id=\"dtb55\" smilref=\"speechgen0005.smil#tcp48\">There's a good chance that all your family members won't be in the same place when disaster strikes, so it's important to have a predetermined rendezvous point. </sent><sent id=\"dtb56\" smilref=\"speechgen0005.smil#tcp49\">Choose a spot that will likely be safe and that is well away from your neighborhood, as you might not be able to make it back to your home. </sent></p></li>"
		+ "							<li><p><sent id=\"dtb57\" smilref=\"speechgen0005.smil#tcp50\">Designate a friend or relative as a contact person that you, your spouse, and your children can call if you can't meet up. </sent><sent smilref=\"speechgen0005.smil#tcp51\" id=\"dtb58\">In order to minimize the chance that the contact person will also be affected by the disaster, choose someone who lives in a distant town or in a different state. </sent><sent smilref=\"speechgen0005.smil#tcp52\" id=\"dtb59\">Make sure that all your family members have the contact person's phone number with them at all times. </sent></p></li>"
		+ "							<li><p><sent id=\"dtb60\" smilref=\"speechgen0005.smil#tcp53\">Discuss disaster scenarios with your family and make sure everyone knows what to do in all the likely emergency scenarios. </sent><sent smilref=\"speechgen0005.smil#tcp54\" id=\"dtb61\">It's important to educate yourself on how to respond to likely hazards, but what happens to your family if they are away from you or if you're killed or injured? </sent><sent smilref=\"speechgen0005.smil#tcp55\" id=\"dtb62\">It's not enough for one person in the family to know what to do--everybody should know the plan. </sent></p></li>"
		+ "							<li>"
		+ "								<p><sent smilref=\"speechgen0005.smil#tcp56\" id=\"dtb63\">Fix potential hazards in your home. </sent><sent smilref=\"speechgen0005.smil#tcp57\" id=\"dtb64\">Once you've identified potential disaster scenarios, thoroughly inspect your house and try to make it as safe as possible. </sent><sent smilref=\"speechgen0005.smil#tcp58\" id=\"dtb65\">Here are just a few examples:</sent></p>"
		+ "								<pagenum page=\"normal\" smilref=\"speechgen0005.smil#tcp59\" id=\"page3\">3</pagenum>"
		+ "							</li>"
		+ "							<li><p><sent smilref=\"speechgen0005.smil#tcp60\" id=\"dtb66\">Every home should have smoke detectors and fire extinguishers. </sent><sent id=\"dtb67\" smilref=\"speechgen0005.smil#tcp61\">Test smoke detectors at least once a month, and replace their batteries yearly or as needed. </sent><sent id=\"dtb68\" smilref=\"speechgen0005.smil#tcp62\">Fire extinguishers should be recharged according to the manufacturer's instructions, and family members should learn how to use them. </sent><sent id=\"dtb69\" smilref=\"speechgen0005.smil#tcp63\">Everyone should also know how to escape the house in the event of a fire. </sent></p></li>"
		+ "							<li><p id=\"dtb70\" smilref=\"speechgen0005.smil#tcp64\">If you live in an area prone to earthquakes, you wouldn't want a tall, heavy bookcase sitting right next to the baby's crib, as it could be knocked over in a quake. </p></li>"
		+ "							<li><p smilref=\"speechgen0005.smil#tcp65\" id=\"dtb71\">If you live near woods with the possibility of forest fires, you should clear your property of brush and high grass to create a buffer zone between your home and the fire. </p></li>"
		+ "							<li><p><sent smilref=\"speechgen0005.smil#tcp66\" id=\"dtb72\">Teach your family basic life-saving techniques. </sent><sent smilref=\"speechgen0005.smil#tcp67\" id=\"dtb73\">Everyone who can learn CPR and first aid should take a certification class and keep their certification current. </sent><sent id=\"dtb74\" smilref=\"speechgen0005.smil#tcp68\">Adults and older children should know how to turn off gas, electricity and water if the house is damaged, and everyone should know how to detect a gas leak. </sent><sent smilref=\"speechgen0005.smil#tcp69\" id=\"dtb75\">Emergency numbers should be posted near phones, and even small children should be taught how to call 9-1-1 or the corresponding emergency number in your country. </sent></p></li>"
		+ "							<li><p><sent id=\"dtb76\" smilref=\"speechgen0005.smil#tcp70\">Assemble a disaster kit. </sent><sent smilref=\"speechgen0005.smil#tcp71\" id=\"dtb77\">Be prepared for emergencies with at least a three-day supply of non-perishable food and potable water, prescription medications, first aid supplies, and other things you might need if you have no utilities and no way to purchase supplies. </sent><sent id=\"dtb78\" smilref=\"speechgen0005.smil#tcp72\">Keep a smaller kit in the trunk of your car. </sent><sent smilref=\"speechgen0005.smil#tcp73\" id=\"dtb79\">See the related wikiHow for more details on building a disaster kit. </sent><sent smilref=\"speechgen0005.smil#tcp74\" id=\"dtb80\">An inexpensive \"pay-as-you-go\" cell phone is a good addition to the kit. </sent></p></li>"
		+ "							<li><p><sent id=\"dtb81\" smilref=\"speechgen0005.smil#tcp75\">Practice your plan. </sent><sent smilref=\"speechgen0005.smil#tcp76\" id=\"dtb82\">Practice makes perfect, and in a life-or-death situation, you want to respond perfectly. </sent><sent smilref=\"speechgen0005.smil#tcp77\" id=\"dtb83\">Periodically go over your emergency plans with your family, and update them as needed. </sent><sent id=\"dtb84\" smilref=\"speechgen0005.smil#tcp78\">Quiz and drill your family on important safety concepts. </sent><sent id=\"dtb85\" smilref=\"speechgen0005.smil#tcp79\">Do a live test with your family; make it an outing and get everyone involved. </sent><sent smilref=\"speechgen0005.smil#tcp80\" id=\"dtb86\">That will help you identify what works and what doesn't. </sent></p></li>"
		+ "							<li><p><sent smilref=\"speechgen0005.smil#tcp81\" id=\"dtb87\">Have contingency plans. </sent><sent smilref=\"speechgen0005.smil#tcp82\" id=\"dtb88\">In the event your emergency site is unavailable or other things change, it's a good idea to have an alternate already identified. </sent></p></li>"
		+ "						</list>"
		+ "					</level3>"
		+ "					<level3>"
		+ "						<h3 id=\"dtb89\" smilref=\"speechgen0006.smil#tcp83\">Tips"
		+ "</h3>"
		+ "						<list id=\"dtb90\" smilref=\"speechgen0006.smil#tcs12\" type=\"ul\">"
		+ "							<li><p><sent id=\"dtb91\" smilref=\"speechgen0006.smil#tcp84\">If your workplace, school, or town hasn't developed an emergency plan, take the initiative to start planning one. </sent><sent id=\"dtb92\" smilref=\"speechgen0006.smil#tcp85\">Go to meetings of local officials and request assistance, and collaborate with your neighbors and coworkers to help make your whole community safer. </sent></p></li>"
		+ "							<li>"
		+ "								<p><sent smilref=\"speechgen0006.smil#tcp86\" id=\"dtb93\">It is a good idea to pick two or three emergency contacts, one who lives outside of your local area code in addition to one who lives within and also someone who can receive text messages. </sent><sent id=\"dtb94\" smilref=\"speechgen0006.smil#tcp87\">In major disasters one can often call a number outside your area code but not within. </sent><sent id=\"dtb95\" smilref=\"speechgen0006.smil#tcp88\">In extreme cases, people have had to rely on text messaging when phone lines and towers were decimated in the disaster. </sent><sent smilref=\"speechgen0006.smil#tcp89\" id=\"dtb96\">After Hurricane Katrina cell phones were just about useless to make calls in the affected areas, but they saved many lives and helped reunite families thanks to their text messaging capabilities that survived. </sent></p>"
		+ "								<pagenum page=\"normal\" id=\"page4\" smilref=\"speechgen0006.smil#tcp90\">4</pagenum>"
		+ "							</li>"
		+ "							<li><p><sent id=\"dtb97\" smilref=\"speechgen0006.smil#tcp91\">Besides the resources mentioned above, you might also want to check with your insurance company for ways to make your house safer. </sent><sent id=\"dtb98\" smilref=\"speechgen0006.smil#tcp92\">Insurers have an interest in minimizing the risk of injury or damage to your home in the event of a disaster, so they will usually be happy to provide you with information. </sent><sent smilref=\"speechgen0006.smil#tcp93\" id=\"dtb99\">Many insurance policies also require certain precautions in order for a loss to be covered. </sent></p></li>"
		+ "							<li><p><sent smilref=\"speechgen0006.smil#tcp94\" id=\"dtb100\">Be serious about your emergency planning, but be careful not to irrationally frighten children or to become obsessed with disaster yourself. </sent><sent id=\"dtb101\" smilref=\"speechgen0006.smil#tcp95\">Planning makes you safer, and it should make you and your family feel safer, too. </sent></p></li>"
		+ "							<li><p><sent id=\"dtb102\" smilref=\"speechgen0006.smil#tcp96\">If you are having difficulty with any of these steps, there are many resources on the internet to assist in this process. </sent><sent id=\"dtb103\" smilref=\"speechgen0006.smil#tcp97\">Check out these sites: Ready.gov, operated by the US Department of Homeland Security and Prepare.org, operated by the American Red Cross. </sent></p></li>"
		+ "							<li>"
		+ "								<p><sent smilref=\"speechgen0006.smil#tcp98\" id=\"dtb104\">Purchase and use \"Self Powered Radios\" and \"Self Powered\" flashlights. </sent><sent id=\"dtb105\" smilref=\"speechgen0006.smil#tcp99\">These do <strong>not</strong> use batteries and are <em>safer</em> than candles. </sent><sent smilref=\"speechgen0006.smil#tcp100\" id=\"dtb106\">Some of these models can also charge your cell phone. </sent></p>"
		+ "							</li>"
		+ "						</list>"
		+ "					</level3>"
		+ "					<level3>"
		+ "						<h3 smilref=\"speechgen0007.smil#tcp101\" id=\"dtb107\">Warnings"
		+ "</h3>"
		+ "						<p><sent smilref=\"speechgen0007.smil#tcp102\" id=\"dtb108\">This is not intended to be a complete guide to disaster preparation. </sent><sent id=\"dtb109\" smilref=\"speechgen0007.smil#tcp103\">You will need to assess the unique set of potential hazards in your area and prepare for them accordingly. </sent></p>"
		+ "						<pagenum id=\"page5\" smilref=\"speechgen0007.smil#tcp104\" page=\"normal\">5</pagenum>"
		+ "					</level3>"
		+ "				</level2>"
		+ "				<level2>"
		+ "					<h2><sent id=\"dtb110\" smilref=\"speechgen0008.smil#tcp105\">2. </sent><sent id=\"dtb111\" smilref=\"speechgen0008.smil#tcp106\">How to Create a Home First Aid Kit"
		+ "</sent></h2>"
		+ "					<p><imggroup><img alt=\"Putting together a first kit at home\" smilref=\"speechgen0008.smil#tcp107\" src=\"image3.jpg\" id=\"rId83\" /></imggroup>"
		+ "					</p>"
		+ "					<p><sent smilref=\"speechgen0008.smil#tcp108\" id=\"dtb112\">Emergencies happen. you can prepare for one by making a first aid kit. </sent><sent id=\"dtb113\" smilref=\"speechgen0008.smil#tcp109\">A first aid kit can be prepared by following the steps given below.</sent></p>"
		+ "					<level3>"
		+ "						<h3 smilref=\"speechgen0009.smil#tcp110\" id=\"dtb114\">Steps"
		+ "</h3>"
		+ "						<list id=\"dtb115\" smilref=\"speechgen0009.smil#tcs13\" type=\"ol\">"
		+ "							<li><p><sent id=\"dtb116\" smilref=\"speechgen0009.smil#tcp111\">Choose a nice sized container. </sent><sent id=\"dtb117\" smilref=\"speechgen0009.smil#tcp112\">It needs to be large enough to store the materials. </sent></p></li>"
		+ "							<li><p><sent smilref=\"speechgen0009.smil#tcp113\" id=\"dtb118\">Store it an easily accessed locale in your home. </sent><sent id=\"dtb119\" smilref=\"speechgen0009.smil#tcp114\">Teach your children and frequent house guests where the first aid kit is stored. </sent></p></li>"
		+ "							<li>"
		+ "								<p id=\"dtb120\" smilref=\"speechgen0009.smil#tcp115\">Fill the box with the following <strong>sterile</strong> and/or <strong>newly-bought</strong> items: </p>"
		+ "								<list type=\"ol\" enum=\"a\" smilref=\"speechgen0009.smil#tcs14\" id=\"dtb121\">"
		+ "									<li><p smilref=\"speechgen0009.smil#tcp116\" id=\"dtb122\">Adhesive dressings, of varied size and shape, from regular Band-Aid shapes to small squares to large </p></li>"
		+ "									<li><p smilref=\"speechgen0009.smil#tcp117\" id=\"dtb123\">Small (but sharp) scissors </p></li>"
		+ "									<li><p><sent id=\"dtb124\" smilref=\"speechgen0009.smil#tcp118\">A package of gauze pads. </sent><sent smilref=\"speechgen0009.smil#tcp119\" id=\"dtb125\">They can be large, because you can always cut them if necessary. </sent></p></li>"
		+ "									<li><p smilref=\"speechgen0009.smil#tcp120\" id=\"dtb126\">Adhesive tape (Not like cellophane tape) </p></li>"
		+ "									<li><p id=\"dtb127\" smilref=\"speechgen0009.smil#tcp121\">Cotton Balls, large and small, or tampons </p></li>"
		+ "									<li>"
		+ "										<p><span class=\"normalized\" smilref=\"speechgen0009.smil#tcp122\" id=\"dtb128\">Rubbing non-Alcohol wipes for <strong><em>cleaning external surfaces only</em></strong> (i.e. cleaning dirt off of <em>unbroken</em>skin, or wiping down a surface) </span> </p>"
		+ "									</li>"
		+ "									<li><p smilref=\"speechgen0009.smil#tcp123\" id=\"dtb129\">Antibiotic Ointment, for keeping the infection out of cuts, scrapes, etc. </p></li>"
		+ "									<li><p smilref=\"speechgen0009.smil#tcp124\" id=\"dtb130\">A thermometer </p></li>"
		+ "									<li><p id=\"dtb131\" smilref=\"speechgen0009.smil#tcp125\">Tweezers for pulling out splinter </p></li>"
		+ "									<li><p smilref=\"speechgen0009.smil#tcp126\" id=\"dtb132\">Non-latex gloves, in case of blood,body fluids and dangerous waste </p></li>"
		+ "									<li><p id=\"dtb133\" smilref=\"speechgen0009.smil#tcp127\">keep two pairs for the smallest kit </p></li>"
		+ "									<li><p smilref=\"speechgen0009.smil#tcp128\" id=\"dtb134\">A bee sting kit </p></li>"
		+ "									<li><p id=\"dtb135\" smilref=\"speechgen0009.smil#tcp129\">Insect Repellant </p></li>"
		+ "									<li><p id=\"dtb136\" smilref=\"speechgen0009.smil#tcp130\">sterile dressings(a sterile pad attached to a roller bandage) </p></li>"
		+ "									<li><p id=\"dtb137\" smilref=\"speechgen0009.smil#tcp131\">roller bandages </p></li>"
		+ "									<li><p smilref=\"speechgen0009.smil#tcp132\" id=\"dtb138\">triangular bandages </p></li>"
		+ "									<li><p smilref=\"speechgen0009.smil#tcp133\" id=\"dtb139\">sterile saline </p></li>"
		+ "									<li><p id=\"dtb140\" smilref=\"speechgen0009.smil#tcp134\">safety pins and bandage clips </p></li>"
		+ "								</list>"
		+ "							</li>"
		+ "						</list>"
		+ "						<pagenum smilref=\"speechgen0009.smil#tcp135\" id=\"page6\" page=\"normal\">6</pagenum>"
		+ "						<p id=\"dtb141\" smilref=\"speechgen0009.smil#tcp136\">You can use these items, if you have no supplies in an emergency: </p>"
		+ "						<list type=\"ul\" smilref=\"speechgen0009.smil#tcs15\" id=\"dtb142\">"
		+ "							<li><p smilref=\"speechgen0009.smil#tcp137\" id=\"dtb143\">sticks for splints </p></li>"
		+ "							<li><p smilref=\"speechgen0009.smil#tcp138\" id=\"dtb144\">cloth for bleeding,slings. </p></li>"
		+ "							<li><p smilref=\"speechgen0009.smil#tcp139\" id=\"dtb145\">Water,to clean wounds and eyes. </p></li>"
		+ "						</list>"
		+ "					</level3>"
		+ "					<level3>"
		+ "						<h3 smilref=\"speechgen0010.smil#tcp140\" id=\"dtb146\">Tips"
		+ "</h3>"
		+ "						<list id=\"dtb147\" smilref=\"speechgen0010.smil#tcs16\" type=\"ol\">"
		+ "							<li><p id=\"dtb148\" smilref=\"speechgen0010.smil#tcp141\">You can also use a store bought kit and and add other items like alcohol or hydrogen peroxide, cotton balls,extra bandages and a thermometer. </p></li>"
		+ "							<li><p smilref=\"speechgen0010.smil#tcp142\" id=\"dtb149\">Cotton swabs are optional </p></li>"
		+ "							<li><p id=\"dtb150\" smilref=\"speechgen0010.smil#tcp143\">For antibiotic ointment, Neosporin is recommended, because it does not sting the cut. </p></li>"
		+ "						</list>"
		+ "						<p><imggroup><img smilref=\"speechgen0010.smil#tcp144\" src=\"image4.jpg\" alt=\"CPR breathing masks\" id=\"rId94\" /></imggroup>"
		+ "						</p>"
		+ "						<p><sent id=\"dtb151\" smilref=\"speechgen0010.smil#tcp145\">You could save a life by learning first aid. </sent><sent smilref=\"speechgen0010.smil#tcp146\" id=\"dtb152\">Go to Your local red cross or other organisation. </sent></p>"
		+ "						<list type=\"ul\" id=\"dtb153\" smilref=\"speechgen0010.smil#tcs17\"><li><p id=\"dtb154\" smilref=\"speechgen0010.smil#tcp147\">Blue items are available for kitcens ECT. </p></li>"
		+ "						</list>"
		+ "						<p><imggroup><img alt=\"sketch showing a person pressing the chest of another person lying on the floor\" smilref=\"speechgen0010.smil#tcp148\" id=\"rId105\" src=\"image5.jpg\" /></imggroup>"
		+ "						</p>"
		+ "						<pagenum id=\"page7\" smilref=\"speechgen0010.smil#tcp149\" page=\"normal\">7</pagenum>"
		+ "					</level3>"
		+ "					<level3>"
		+ "						<h3 id=\"dtb155\" smilref=\"speechgen0011.smil#tcp150\">Warnings"
		+ "</h3>"
		+ "						<list smilref=\"speechgen0011.smil#tcs18\" id=\"dtb156\" type=\"ol\">"
		+ "							<li><p smilref=\"speechgen0011.smil#tcp151\" id=\"dtb157\">Wash tweezers, scissors, and thermometer after each use. </p></li>"
		+ "							<li><p smilref=\"speechgen0011.smil#tcp152\" id=\"dtb158\">Be aware of what you use and don't let supplies get low! </p></li>"
		+ "							<li><p smilref=\"speechgen0011.smil#tcp153\" id=\"dtb159\">Be sure everyone who would potentially use the kit is not allergic to any of the ingredients. </p></li>"
		+ "							<li><p smilref=\"speechgen0011.smil#tcp154\" id=\"dtb160\">Do not store prescriptions in the first aid kit,items such as an epipen are all right though </p></li>"
		+ "							<li><p smilref=\"speechgen0011.smil#tcp155\" id=\"dtb161\">Don't use any products containing natural rubber latex (NRL), someone could be allergic. </p></li>"
		+ "						</list>"
		+ "						<pagenum id=\"page8\" page=\"normal\" smilref=\"speechgen0011.smil#tcp156\">8</pagenum>"
		+ "					</level3>"
		+ "				</level2>"
		+ "				<level2>"
		+ "					<h2><sent id=\"dtb162\" smilref=\"speechgen0012.smil#tcp157\">3. </sent><sent smilref=\"speechgen0012.smil#tcp158\" id=\"dtb163\">How to Administer Adult CPR (Cardiopulmonary Resuscitation)"
		+ "</sent></h2>"
		+ "					<p><imggroup><img alt=\"showing Adult CPR \" src=\"image11.jpg\" id=\"rId1611\" smilref=\"speechgen0012.smil#tcp159\" /></imggroup>"
		+ "					</p>"
		+ "					<p><sent smilref=\"speechgen0012.smil#tcp160\" id=\"dtb164\">Let's hope you never have to be put in the situation where someone is in need of CPR. </sent><sent id=\"dtb165\" smilref=\"speechgen0012.smil#tcp161\">In case you are, it would be helpful to be informed on how to perform this technique. </sent><sent id=\"dtb166\" smilref=\"speechgen0012.smil#tcp162\">You may end up saving a person's life. </sent><sent smilref=\"speechgen0012.smil#tcp163\" id=\"dtb167\">These instructions are for an adult only (infants and children differ). </sent><sent><strong id=\"dtb168\" smilref=\"speechgen0012.smil#tcp164\">Be aware that different organizations teach different methods for administering CPR.</strong> </sent><sent smilref=\"speechgen0012.smil#tcp165\" id=\"dtb169\">Use these instructions only for refreshing techniques learned from a certified CPR instructor.</sent></p>"
		+ "					<level3>"
		+ "						<h3 smilref=\"speechgen0013.smil#tcp166\" id=\"dtb170\">Steps"
		+ "</h3>"
		+ "						<list id=\"dtb171\" smilref=\"speechgen0013.smil#tcs19\" type=\"ol\">"
		+ "							<li><p smilref=\"speechgen0013.smil#tcp167\" id=\"dtb172\"><strong>Perform</strong> CPR only if certified. </p>"
		+ "							</li>"
		+ "							<li>"
		+ "								<p><sent><strong id=\"dtb173\" smilref=\"speechgen0013.smil#tcp168\">Check the scene for safety</strong>. </sent><sent smilref=\"speechgen0013.smil#tcp169\" id=\"dtb174\">Is there a car exhaust running? </sent><sent smilref=\"speechgen0013.smil#tcp170\" id=\"dtb175\">A gas stove? </sent><sent smilref=\"speechgen0013.smil#tcp171\" id=\"dtb176\">Is there a fire? </sent></p>"
		+ "								<list enum=\"a\" id=\"dtb177\" type=\"ol\" smilref=\"speechgen0013.smil#tcs20\">"
		+ "									<li><p><sent smilref=\"speechgen0013.smil#tcp172\" id=\"dtb178\">If there is anything that could endanger you or the victim, see if there is something you can do to counteract it. </sent><sent id=\"dtb179\" smilref=\"speechgen0013.smil#tcp173\">Open a window, turn off the stove, or put out the fire if possible. </sent><sent smilref=\"speechgen0013.smil#tcp174\" id=\"dtb180\">Anything you can do to counteract the danger. </sent></p></li>"
		+ "									<li><p><sent id=\"dtb181\" smilref=\"speechgen0013.smil#tcp175\">However, if there is nothing you can do to counteract the danger, move the victim. </sent><sent smilref=\"speechgen0013.smil#tcp176\" id=\"dtb182\">The best way to move the victim is by placing a blanket or a coat underneath their back and pulling on the coat or blanket. </sent></p></li>"
		+ "								</list>"
		+ "							</li>"
		+ "							<li>"
		+ "								<p><sent smilref=\"speechgen0013.smil#tcp177\" id=\"dtb183\">Now that the scene is safe, <strong>check the victim for consciousness</strong> by shaking or tapping their shoulder and saying in a loud, clear voice, \"Are you okay? </sent><sent id=\"dtb184\" smilref=\"speechgen0013.smil#tcp178\">Are you okay?\" </sent></p>"
		+ "								<list smilref=\"speechgen0013.smil#tcs21\" enum=\"a\" type=\"ol\" id=\"dtb185\">"
		+ "									<li><p><sent id=\"dtb186\" smilref=\"speechgen0013.smil#tcp179\">If they respond, they are conscious. </sent><sent id=\"dtb187\" smilref=\"speechgen0013.smil#tcp180\">They may have just been sleeping, or they could have been unconscious. </sent><sent id=\"dtb188\" smilref=\"speechgen0013.smil#tcp181\">If it still appears to be an emergency situation (<abbr title=\"for example\">e.g.</abbr> they are having trouble breathing, they appear to be fading in between consciousness and unconsciousness, they were unconscious, etc.) continue on to the next step. </sent><sent smilref=\"speechgen0013.smil#tcp182\" id=\"dtb189\">If they were conscious, but the situation still appears to be an emergency, check for injuries, broken bones, etc. </sent></p></li>"
		+ "									<li><p id=\"dtb190\" smilref=\"speechgen0013.smil#tcp183\">If they do not respond, continue on to the next step. </p></li>"
		+ "								</list>"
		+ "							</li>"
		+ "							<li>"
		+ "								<p><sent><strong id=\"dtb191\" smilref=\"speechgen0013.smil#tcp184\">Send for help</strong>. </sent><sent smilref=\"speechgen0013.smil#tcp185\" id=\"dtb192\">The more people available for this step the better, however, it can be done alone. </sent><sent id=\"dtb193\" smilref=\"speechgen0013.smil#tcp186\">Send someone to call the Emergency Medical Services (<acronym pronounce=\"no\" title=\"European Monetary System\">EMS</acronym>). </sent><sent id=\"dtb194\" smilref=\"speechgen0013.smil#tcp187\">Call <strong>911</strong> in North America, <strong>000</strong> in Australia, <strong>112</strong> by cellphone in the <acronym title=\"European Union\" pronounce=\"no\">EU</acronym> (including the <acronym title=\"United Kingdom\" pronounce=\"no\">UK</acronym>) and <strong>999</strong> in the <acronym title=\"United Kingdom\" pronounce=\"no\">UK</acronym>. </sent><sent smilref=\"speechgen0013.smil#tcp188\" id=\"dtb195\">And make sure you point to them and say \"Go call 911\" (or whatever the <acronym title=\"European Monetary System\" pronounce=\"no\">EMS</acronym> number is in your area). </sent><sent smilref=\"speechgen0013.smil#tcp189\" id=\"dtb196\">This way you'll make sure you specifically sent for help. </sent><sent smilref=\"speechgen0013.smil#tcp190\" id=\"dtb197\">If you are alone, preform CPR for one minute (which is about three cycles of CPR) and then call the <acronym title=\"European Monetary System\" pronounce=\"no\">EMS</acronym>, then resume. </sent><sent smilref=\"speechgen0013.smil#tcp191\" id=\"dtb198\">If possible, send someone else to get an AED (Automatic External Defibrillator) if there is one in the building. </sent></p>"
		+ "							</li>"
		+ "							<li>"
		+ "								<p><strong id=\"dtb199\" smilref=\"speechgen0013.smil#tcp192\">Check for signs of life: </strong></p>"
		+ "								<list id=\"dtb200\" smilref=\"speechgen0013.smil#tcs22\" enum=\"a\" type=\"ol\"><li><p><sent id=\"dtb201\" smilref=\"speechgen0013.smil#tcp193\">Place your hand on the victims forehead and two fingers on their chin and tilt the head back slightly to open the airway. </sent><sent smilref=\"speechgen0013.smil#tcp194\" id=\"dtb202\">Place your cheek above their mouth and stare at their chest (you cheeks have a lot of nerves in it, so it's easier to feel the patients breath). </sent><sent smilref=\"speechgen0013.smil#tcp195\" id=\"dtb203\">Do this for ten seconds, if you do not feel a breath or see the chest rising, continue to the next step. </sent><sent id=\"dtb204\" smilref=\"speechgen0013.smil#tcp196\">If there are signs of life, treat for shock. </sent><sent smilref=\"speechgen0013.smil#tcp197\" id=\"dtb205\">Cover them if it is cold, and if possible, uncover them if it is hot, etc. </sent></p></li>"
		+ "								</list>"
		+ "							</li>"
		+ "							<li><p id=\"dtb206\" smilref=\"speechgen0013.smil#tcp198\">If there are no signs of life, <strong>place a breathing barrier</strong> over the victim's mouth. </p>"
		+ "							</li>"
		+ "							<li><p><sent smilref=\"speechgen0013.smil#tcp199\" id=\"dtb207\"><strong>Give two rescue breaths</strong> Keeping the airway open, take the fingers that were on the forehead and pinch the victim's nose closed. </sent><sent smilref=\"speechgen0013.smil#tcp200\" id=\"dtb208\">Make a seal with your mouth over the victim's mouth and breathe out for about one second. </sent><sent id=\"dtb209\" smilref=\"speechgen0013.smil#tcp201\">Make sure you breath slowly, as this will make sure the air goes in the lungs not the stomach. </sent><sent id=\"dtb210\" smilref=\"speechgen0013.smil#tcp202\">Also make sure you keep your eye on the victim's chest. </sent><sent id=\"dtb211\" smilref=\"speechgen0013.smil#tcp203\">If the breath goes in, you should see the chest slightly rise and also feel it go in. </sent><sent smilref=\"speechgen0013.smil#tcp204\" id=\"dtb212\">If the breath goes in, give a second rescue breath. </sent><sent smilref=\"speechgen0013.smil#tcp205\" id=\"dtb213\">If the breath does not go in, re-position the head and try again. </sent><sent id=\"dtb214\" smilref=\"speechgen0013.smil#tcp206\">If it does not go in again, the victim may be choking. </sent></p>"
		+ "							</li>"
		+ "							<li><p><sent id=\"dtb215\" smilref=\"speechgen0013.smil#tcp207\">Place your hands on top of each other and place them in the center of the chest (on the <strong>breastbone</strong>) between the two nipples. </sent><sent id=\"dtb216\" smilref=\"speechgen0013.smil#tcp208\">Your ring finger should be on top of the nipple (this will lower the chances of breaking a rib or ribs). </sent></p>"
		+ "							</li>"
		+ "							<li><p><sent smilref=\"speechgen0013.smil#tcp209\" id=\"dtb217\">Compress the chest by pushing straight down approximately two inches deep. </sent><sent id=\"dtb218\" smilref=\"speechgen0013.smil#tcp210\">Do thirty of these compressions, and do them fast, approximately 30 compressions in 30 seconds. </sent></p></li>"
		+ "							<li><p id=\"dtb219\" smilref=\"speechgen0013.smil#tcp211\">Repeat Steps 6 through 8 for one minute, delivering two rescue breaths every 30 seconds/compressions. </p></li>"
		+ "							<li><p id=\"dtb220\" smilref=\"speechgen0013.smil#tcp212\">Recheck for signs of life. </p></li>"
		+ "							<li><p smilref=\"speechgen0013.smil#tcp213\" id=\"dtb221\">Continue CPR until someone takes over for you, emergency personnel arrive, you are too exhausted to continue or an AED is available for immediate use, or pulse and breathing return. </p></li>"
		+ "						</list>"
		+ "						<pagenum page=\"normal\" id=\"page9\" smilref=\"speechgen0013.smil#tcp214\">9</pagenum>"
		+ "					</level3>"
		+ "					<level3>"
		+ "						<h3 id=\"dtb222\" smilref=\"speechgen0014.smil#tcp215\">Tips"
		+ "</h3>"
		+ "						<list id=\"dtb223\" type=\"ol\" smilref=\"speechgen0014.smil#tcs23\">"
		+ "							<li><p id=\"dtb224\" smilref=\"speechgen0014.smil#tcp216\">Don't forget to place your hands in the middle of the breastbone at the level of the nipples. </p></li>"
		+ "							<li><p smilref=\"speechgen0014.smil#tcp217\" id=\"dtb225\">When moving the victim, try to disturb the body as little as possible. </p></li>"
		+ "							<li><p id=\"dtb226\" smilref=\"speechgen0014.smil#tcp218\">ALWAYS call the Emergency Medical Services. </p></li>"
		+ "							<li><p><sent smilref=\"speechgen0014.smil#tcp219\" id=\"dtb227\">Get trained! </sent><sent id=\"dtb228\" smilref=\"speechgen0014.smil#tcp220\">You get to learn and practice your skills under the supervision of a trained instructor with the help of a video presentation and CPR training mannequin (\"dummy\"). </sent></p></li>"
		+ "							<li><p id=\"dtb229\" smilref=\"speechgen0014.smil#tcp221\">If you feel the area is unsafe to enter, and it is not safe to move the victim, stay where you are and either send someone to call Emergency Medical Services, or do so yourself and stay with the victim! </p></li>"
		+ "							<li><p smilref=\"speechgen0014.smil#tcp222\" id=\"dtb230\">Remember that if a person can talk in full sentences, they are breathing, and if they are breathing, they probably have a pulse. </p></li>"
		+ "							<li><p id=\"dtb231\" smilref=\"speechgen0014.smil#tcp223\">Even \"bad\" CPR is better than no CPR! </p></li>"
		+ "						</list>"
		+ "					</level3>"
		+ "					<level3>"
		+ "						<h3 smilref=\"speechgen0015.smil#tcp224\" id=\"dtb232\">Warnings"
		+ "</h3>"
		+ "						<list id=\"dtb233\" smilref=\"speechgen0015.smil#tcs24\" type=\"ol\">"
		+ "							<li><p><sent smilref=\"speechgen0015.smil#tcp225\" id=\"dtb234\">You should learn this at a certified CPR class. </sent><sent id=\"dtb235\" smilref=\"speechgen0015.smil#tcp226\">Training organizations such as the American Heart Association, American Red Cross and other societies in many countries offer such classes. </sent><sent id=\"dtb236\" smilref=\"speechgen0015.smil#tcp227\">If you have no knowledge of CPR, go to one of the classes. </sent><sent smilref=\"speechgen0015.smil#tcp228\" id=\"dtb237\">They will show you how to do this without mistakes, which are very crucial. </sent></p></li>"
		+ "							<li><p smilref=\"speechgen0015.smil#tcp229\" id=\"dtb238\">Be sure to survey the scene for danger before you attempt to administer CPR. </p></li>"
		+ "							<li><p id=\"dtb239\" smilref=\"speechgen0015.smil#tcp230\">Remember that CPR is different for adults, children and infants; this CPR is meant to be administered to an adult. </p></li>"
		+ "							<li><p id=\"dtb240\" smilref=\"speechgen0015.smil#tcp231\">Always practice CPR with a breathing barrier to prevent disease transmission. </p></li>"
		+ "							<li><p smilref=\"speechgen0015.smil#tcp232\" id=\"dtb241\">Don't worry if you break ribs - these can be fixed, being dead can't. </p></li>"
		+ "							<li><p id=\"dtb242\" smilref=\"speechgen0015.smil#tcp233\">Do not move the patient unless they are in immediate danger or are in a place that is life threatening. </p></li>"
		+ "							<li><p smilref=\"speechgen0015.smil#tcp234\" id=\"dtb243\">Always wear gloves and use a face shield or some other sort of barrier when possible. </p></li>"
		+ "						</list>"
		+ "						<pagenum page=\"normal\" smilref=\"speechgen0015.smil#tcp235\" id=\"page10\">10</pagenum>"
		+ "					</level3>"
		+ "				</level2>"
		+ "			</level1>"
		+ "		</bodymatter>"
		+ "	</book>"
		+ "</dtbook>";
}
